import csv
import json
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src import training_params as params
from src.config import make_config
from src.sumo_env import SumoMultiAgentEnv


REQUIRED_TRAIN_COLUMNS = {
    "avg_vehicle_reward_component",
    "avg_pedestrian_reward_component",
    "pedestrian_reward_share",
}


def validation_env(force_retrain: bool = False) -> dict:
    env = os.environ.copy()
    env.update(
        {
            "PYTHONIOENCODING": "utf-8",
            "BFU_FAST_TEST": "1",
            "BFU_FORCE_RETRAIN": "1" if force_retrain else "0",
            "BFU_EPISODE_SECONDS": "120",
            "BFU_TRAIN_SECONDS": "300",
            "BFU_EVAL_EPISODES": "1",
            "BFU_EVAL_SEEDS": "42",
        }
    )
    return env


def run_main(force_retrain: bool = False) -> None:
    result = subprocess.run(
        [sys.executable, "main.py"],
        cwd=ROOT,
        env=validation_env(force_retrain=force_retrain),
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        timeout=360,
    )
    (ROOT / "logs").mkdir(exist_ok=True)
    (ROOT / "logs" / "validation_pedestrian_reward_main_stdout.txt").write_text(
        result.stdout,
        encoding="utf-8",
    )
    (ROOT / "logs" / "validation_pedestrian_reward_main_stderr.txt").write_text(
        result.stderr,
        encoding="utf-8",
    )
    assert result.returncode == 0, result.stdout + result.stderr


def scenario_has_pedestrians() -> bool:
    for path in (ROOT / "scenario").glob("*.xml"):
        if path.name == "autogenerated_pedestrians.rou.xml" and path.exists():
            return True
        text = path.read_text(encoding="utf-8", errors="ignore")
        if "<person" in text or "<personFlow" in text or "<walk" in text:
            return True
    return False


def train_metrics_have_reward_columns() -> bool:
    path = ROOT / "logs" / "train_metrics.csv"
    if not path.exists() or path.stat().st_size == 0:
        return False
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        header = set(reader.fieldnames or [])
        return REQUIRED_TRAIN_COLUMNS.issubset(header)


def validate_eval_reward_breakdown() -> dict:
    eval_path = ROOT / "logs" / "eval_rl.json"
    assert eval_path.exists(), "logs/eval_rl.json does not exist"
    data = json.loads(eval_path.read_text(encoding="utf-8"))
    breakdown = data.get("reward_breakdown")
    assert isinstance(breakdown, dict), "eval_rl.json missing reward_breakdown"
    assert breakdown.get("avg_pedestrian_reward_component") is not None
    assert breakdown.get("avg_vehicle_reward_component") is not None
    share = float(breakdown.get("pedestrian_reward_share", 0.0) or 0.0)
    if share > 0.3:
        message = "pedestrian_reward_share is too high; vehicle priority may be lost"
        if getattr(params, "STRICT_REWARD_VALIDATION", True):
            raise AssertionError(message)
        print("WARNING: " + message)
    return breakdown


def validate_train_metrics() -> None:
    path = ROOT / "logs" / "train_metrics.csv"
    assert path.exists(), "logs/train_metrics.csv does not exist"
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        header = set(reader.fieldnames or [])
        missing = REQUIRED_TRAIN_COLUMNS.difference(header)
        assert not missing, f"train_metrics.csv missing columns: {sorted(missing)}"
        rows = list(reader)
    assert rows, "train_metrics.csv has no rows"
    assert any(row.get("avg_pedestrian_reward_component") not in {"", None} for row in rows), (
        "avg_pedestrian_reward_component was not recorded"
    )


def validate_pedestrian_toggle() -> None:
    cfg = make_config(ROOT)
    env = SumoMultiAgentEnv.__new__(SumoMultiAgentEnv)
    env.obs_cfg = cfg
    metrics = {
        "pedestrian_waiting_time_available": True,
        "pedestrian_avg_waiting_time": 12.0,
        "pedestrian_running": 6,
        "pedestrian_waiting_count": 3,
    }
    enabled_penalty = env._compute_pedestrian_reward_penalty(metrics)
    assert enabled_penalty > 0.0, "pedestrian penalty is zero when reward is enabled"

    cfg.reward_use_pedestrians = False
    disabled_penalty = env._compute_pedestrian_reward_penalty(metrics)
    assert disabled_penalty == 0.0, "pedestrian penalty is non-zero when reward is disabled"


def main() -> int:
    try:
        assert params.REWARD_USE_PEDESTRIANS is True, "REWARD_USE_PEDESTRIANS must be enabled by default"
        if not scenario_has_pedestrians() or not train_metrics_have_reward_columns():
            run_main(force_retrain=True)
        else:
            run_main(force_retrain=False)
        assert scenario_has_pedestrians(), "scenario has no pedestrians after main.py"
        validate_train_metrics()
        validate_eval_reward_breakdown()
        validate_pedestrian_toggle()
        print("PEDESTRIAN REWARD VALIDATION PASSED")
        return 0
    except Exception as exc:
        print(f"PEDESTRIAN REWARD VALIDATION FAILED: {type(exc).__name__}: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
