import shutil
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.checkpointing import build_checkpoint_metadata, checkpoint_file_exists, validate_checkpoint_compatibility
from src.config import make_config
from src.sumo_env import SumoMultiAgentEnv


def metadata_for_config(cfg) -> dict:
    env = None
    try:
        env = SumoMultiAgentEnv(
            cfg.scenario_dir,
            use_gui=False,
            step_length=cfg.step_length,
            episode_seconds=int(cfg.episode_seconds),
            min_green=cfg.min_green,
            alpha=cfg.alpha,
            beta=cfg.beta,
            obs_cfg=cfg,
            seed=cfg.seed,
            sumo_extra_args=cfg.sumo_extra_args,
        )
        obs = env.reset()
        return build_checkpoint_metadata(
            cfg,
            env.scenario,
            env.tls_ids,
            len(next(iter(obs.values()))),
            env.num_phases_per_tls,
        )
    finally:
        if env is not None:
            env.close()


def main() -> int:
    try:
        cfg = make_config(ROOT)
        cfg.debug_scenario = False
        cfg.episode_seconds = 120
        cfg.train_steps = 120
        cfg.eval_episodes = 1
        cfg.eval_seeds = [42]
        current = metadata_for_config(cfg)
        if checkpoint_file_exists(cfg.checkpoint_path) and cfg.checkpoint_meta_path.exists():
            compatible, reason = validate_checkpoint_compatibility(cfg, current)
            if not compatible:
                env = os.environ.copy()
                env.update(
                    {
                        "PYTHONIOENCODING": "utf-8",
                        "BFU_FAST_TEST": "1",
                        "BFU_EPISODE_SECONDS": "120",
                        "BFU_TRAIN_SECONDS": "120",
                        "BFU_EVAL_EPISODES": "1",
                        "BFU_EVAL_SEEDS": "42",
                    }
                )
                result = subprocess.run(
                    [sys.executable, "main.py"],
                    cwd=ROOT,
                    env=env,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                    capture_output=True,
                    timeout=180,
                )
                assert result.returncode == 0, (
                    "could not refresh incompatible checkpoint before signature validation: "
                    + result.stdout
                    + result.stderr
                )
                current = metadata_for_config(cfg)
                compatible, reason = validate_checkpoint_compatibility(cfg, current)
                assert compatible, f"current checkpoint metadata is not compatible after refresh: {reason}"

        tmp_root = ROOT / "tmp_validation_signature_scenario"
        if tmp_root.exists():
            shutil.rmtree(tmp_root)
        tmp_root.mkdir(parents=True)
        for source in cfg.scenario_dir.glob("*"):
            if source.is_file():
                shutil.copy2(source, tmp_root / source.name)

        route_files = sorted(
            [
                path
                for path in list(tmp_root.glob("*.rou.xml")) + list(tmp_root.glob("*.trips.xml"))
                if path.name != "autogenerated_pedestrians.rou.xml"
            ]
        )
        assert route_files, "no route files found for signature mutation"
        with route_files[0].open("a", encoding="utf-8") as f:
            f.write("\n<!-- validation signature mutation -->\n")

        tmp_cfg = make_config(ROOT)
        tmp_cfg.scenario_dir_name = tmp_root.name
        tmp_cfg.debug_scenario = False
        tmp_cfg.episode_seconds = 120
        tmp_cfg.train_steps = 120
        tmp_cfg.eval_episodes = 1
        tmp_cfg.eval_seeds = [42]
        changed = metadata_for_config(tmp_cfg)
        assert (
            current["scenario_signature"] != changed["scenario_signature"]
        ), "scenario_signature did not change after route-file content mutation"

        if checkpoint_file_exists(cfg.checkpoint_path) and cfg.checkpoint_meta_path.exists():
            compatible, _ = validate_checkpoint_compatibility(cfg, changed)
            assert not compatible, "old checkpoint was considered compatible with changed scenario signature"

        shutil.rmtree(tmp_root, ignore_errors=True)
        print("SCENARIO SIGNATURE VALIDATION PASSED")
        return 0
    except Exception as exc:
        print(f"SCENARIO SIGNATURE VALIDATION FAILED: {type(exc).__name__}: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
