import json
import os
import subprocess
import sys
import time
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass
from pathlib import Path
from xml.sax.saxutils import escape

from .config import make_config
from .eval import evaluate
from .logging_utils import save_json, write_csv_row
from .objectives import add_normalized_metrics, objective_payload
from .scenario import (
    AUTOGENERATED_DIAGNOSTIC_DEMAND,
    discover_scenario,
    generate_pedestrian_demand,
)
from .train import train
from .utils import add_sumo_tools_to_path, check_python_dependencies, check_sumo_installation, safe_mkdir, set_seed


@dataclass
class DiplomaRun:
    mode: str
    train_episodes: int
    train_episode_seconds: int
    eval_seconds: int
    vehicle_count: int
    pedestrian_count: int
    controlled_tls: int | None
    device: str = "auto"
    seed: int = 42


def default_run(mode: str) -> DiplomaRun:
    mode = normalize_mode(mode)
    if mode == "fast":
        return DiplomaRun("fast", 1, 10, 60, 80, 40, 2, "cpu", 42)
    if mode == "validate_fast":
        return DiplomaRun("validate_fast", 1, 10, 60, 80, 40, 2, "cpu", 42)
    if mode == "long":
        return DiplomaRun("long", 40, 600, 1800, 1000, 150, None, "auto", 42)
    if mode == "manual":
        base = default_run("normal")
        base.mode = "manual"
        return base
    return DiplomaRun("normal", 10, 300, 900, 300, 50, 50, "auto", 42)


def normalize_mode(value: str) -> str:
    value = str(value or "normal").strip().lower()
    return {
        "1": "fast",
        "fast": "fast",
        "быстрый": "fast",
        "2": "normal",
        "normal": "normal",
        "нормальный": "normal",
        "3": "long",
        "long": "long",
        "долгий": "long",
        "4": "manual",
        "manual": "manual",
        "ручной": "manual",
        "validate_fast": "validate_fast",
    }.get(value, value)


def run(project_root: Path) -> int:
    project_root = Path(project_root).resolve()
    _configure_console()
    setup = resolve_setup()
    if setup is None:
        return 1

    ok, details = check_sumo_installation()
    if not ok:
        print(details or "SUMO/TraCI недоступен.")
        return 1
    ok, details = check_python_dependencies()
    if not ok:
        print(f"Не хватает Python-зависимостей: {details}")
        return 1

    cfg = make_config(project_root)
    apply_setup(cfg, setup)

    started = time.perf_counter()
    safe_mkdir(cfg.logs_dir)
    safe_mkdir(cfg.checkpoints_dir)
    safe_mkdir(cfg.scenario_dir)
    set_seed(setup.seed)

    scenario, selected_tls, pedestrian_meta = prepare_scenario(cfg, setup)
    print_summary(setup, scenario, selected_tls, pedestrian_meta)

    print()
    print("Training")
    print("--------")
    train_result = train(cfg)

    original_seconds = int(cfg.episode_seconds)
    cfg.episode_seconds = int(setup.eval_seconds)
    cfg.eval_episodes = 1
    try:
        print()
        print("Evaluation")
        print("----------")
        rl_metrics = evaluate(cfg, mode="rl", episodes=1)
        print("RL: done")
        fixed_metrics = evaluate(cfg, mode="fixed_native", episodes=1)
        print("fixed-time: done")
    finally:
        cfg.episode_seconds = original_seconds

    comparison = build_comparison(rl_metrics, fixed_metrics)
    save_outputs(cfg, setup, selected_tls, pedestrian_meta, train_result, rl_metrics, fixed_metrics, comparison)
    print_comparison(comparison)
    print_action_diagnostics(rl_metrics, fixed_metrics)
    print_runtime(started, train_result)
    return validate_result(rl_metrics, fixed_metrics, comparison, pedestrian_meta)


def resolve_setup() -> DiplomaRun | None:
    non_interactive = os.environ.get("BFU_NON_INTERACTIVE", "").strip().lower() in {"1", "true", "yes", "on"}
    if non_interactive:
        setup = default_run(os.environ.get("BFU_RUN_MODE", "normal"))
        apply_env_overrides(setup)
        return setup

    while True:
        print("1) Быстрый")
        print("2) Нормальный")
        print("3) Долгий")
        print("4) Ручной")
        try:
            choice = input("Выберите режим: ").strip() or "2"
        except (EOFError, KeyboardInterrupt):
            print()
            print("Запуск остановлен пользователем.")
            return None
        mode = normalize_mode(choice)
        if mode in {"fast", "normal", "long", "manual"}:
            break
        print("Некорректный режим. Введите 1, 2, 3 или 4.")
    setup = default_run(mode)
    if mode == "manual":
        setup = prompt_manual(setup)
    return setup


def prompt_manual(setup: DiplomaRun) -> DiplomaRun:
    return DiplomaRun(
        mode="manual",
        train_episodes=prompt_int("Количество эпизодов обучения [1 - 100]", setup.train_episodes, 1, 100),
        train_episode_seconds=prompt_int("Время одного эпизода, сек. [45 - 1800]", setup.train_episode_seconds, 45, 1800),
        eval_seconds=prompt_int("Время evaluation, сек. [30 - 3600]", setup.eval_seconds, 30, 3600),
        vehicle_count=prompt_int("Количество машин [20 - 5000]", setup.vehicle_count, 20, 5000),
        pedestrian_count=prompt_int("Количество пешеходов [0 - 1000]", setup.pedestrian_count, 0, 1000),
        controlled_tls=prompt_tls("Управляемые светофоры [1 - 270, all]", setup.controlled_tls),
        device=prompt_choice("Устройство [auto/cuda/cpu]", setup.device, {"auto", "cuda", "cpu"}),
        seed=setup.seed,
    )


def prompt_int(prompt: str, default: int, min_value: int, max_value: int) -> int:
    while True:
        raw = input(f"{prompt} ({default}): ").strip()
        if not raw:
            return int(default)
        try:
            value = int(raw)
        except ValueError:
            print("Введите целое число.")
            continue
        if min_value <= value <= max_value:
            return value
        print(f"Допустимый диапазон: {min_value} - {max_value}.")


def prompt_tls(prompt: str, default: int | None) -> int | None:
    raw_default = "all" if default is None else str(default)
    while True:
        raw = input(f"{prompt} ({raw_default}): ").strip().lower()
        if not raw:
            return default
        if raw == "all":
            return None
        try:
            value = int(raw)
        except ValueError:
            print("Введите число или all.")
            continue
        if 1 <= value <= 270:
            return value
        print("Допустимый диапазон: 1 - 270.")


def prompt_choice(prompt: str, default: str, allowed: set[str]) -> str:
    while True:
        raw = input(f"{prompt} ({default}): ").strip().lower()
        if not raw:
            return default
        if raw in allowed:
            return raw
        print(f"Допустимо: {', '.join(sorted(allowed))}.")


def apply_env_overrides(setup: DiplomaRun) -> None:
    for env_name, attr in {
        "BFU_TRAIN_EPISODES": "train_episodes",
        "BFU_TRAIN_EPISODE_SECONDS": "train_episode_seconds",
        "BFU_EVAL_SECONDS": "eval_seconds",
        "BFU_VEHICLE_COUNT": "vehicle_count",
        "BFU_PEDESTRIAN_COUNT": "pedestrian_count",
        "BFU_SEED": "seed",
    }.items():
        if os.environ.get(env_name):
            setattr(setup, attr, int(os.environ[env_name]))
    if os.environ.get("BFU_CONTROLLED_TLS"):
        value = os.environ["BFU_CONTROLLED_TLS"].strip().lower()
        setup.controlled_tls = None if value == "all" else int(value)
    if os.environ.get("BFU_DEVICE"):
        setup.device = os.environ["BFU_DEVICE"].strip().lower()


def apply_setup(cfg, setup: DiplomaRun) -> None:
    cfg.run_mode = setup.mode
    cfg.log_level = "compact"
    cfg.device = setup.device
    cfg.require_cuda = setup.device == "cuda"
    cfg.use_gui = False
    cfg.seed = setup.seed
    cfg.eval_seeds = [setup.seed]
    cfg.episode_seconds = int(setup.train_episode_seconds)
    cfg.train_episodes = int(setup.train_episodes)
    cfg.train_steps = int(setup.train_episodes) * int(setup.train_episode_seconds)
    cfg.evaluation_seconds = int(setup.eval_seconds)
    cfg.max_controlled_tls = setup.controlled_tls
    cfg.controlled_tls_mode = "active_only"
    cfg.demand_mode = "generated_diagnostic"
    cfg.vehicle_count = int(setup.vehicle_count)
    cfg.vehicle_depart_start = 0
    cfg.vehicle_depart_end = int(setup.eval_seconds)
    cfg.auto_generate_pedestrians_if_missing = setup.pedestrian_count > 0
    cfg.pedestrians_requested = setup.pedestrian_count > 0
    cfg.pedestrian_demand_count = int(setup.pedestrian_count)
    cfg.pedestrian_demand_begin = 0
    cfg.pedestrian_demand_end = int(setup.eval_seconds)
    cfg.pedestrian_mode = "crossing_focused"
    cfg.force_retrain = os.environ.get("BFU_FORCE_RETRAIN", "1").strip().lower() not in {"0", "false", "no", "off"}
    cfg.use_tuning = False
    cfg.run_native_fixed_baseline = True
    cfg.run_real_timing_baseline = False
    cfg.rl_use_real_timing_program_as_base = False
    cfg.sumo_parallel_eval = False
    cfg.progress_bar_style = os.environ.get("BFU_PROGRESS_BAR_STYLE", "single_line")
    cfg.print_scenario_info = False
    cfg.save_eval_logs = True
    cfg.save_train_logs = True
    cfg.reward_use_pedestrians = True
    cfg.pedestrian_reward_enabled = True
    cfg.use_double_dqn = True
    cfg.use_dueling_dqn = True
    cfg.algorithm = "double_dueling_dqn"
    cfg.grad_clip_norm = 10.0
    quick_mode = setup.mode in {"fast", "validate_fast"}
    cfg.batch_size = 8 if quick_mode else min(int(getattr(cfg, "batch_size", 128)), 128)
    cfg.start_learning_after = 4 if quick_mode else min(int(getattr(cfg, "start_learning_after", 256)), int(cfg.batch_size))
    cfg.train_freq = 1
    cfg.target_update_freq = 100
    cfg.validation_every_episodes = 0
    cfg.validation_seconds = 0
    cfg.quality_gate_enabled = False
    cfg.eval_epsilon = 0.10 if quick_mode else 0.0
    cfg.evaluation_mode = "rl_epsilon_diagnostic" if cfg.eval_epsilon > 0 else "rl_greedy"
    cfg.min_switch_action_prob_during_train = max(float(getattr(cfg, "min_switch_action_prob_during_train", 0.0)), 0.20)
    cfg.smoke_skip_tls_graph = True
    cfg.checkpoint_name = "diploma_dqn.pt"
    cfg.checkpoint_meta_name = "diploma_dqn_meta.json"


def prepare_scenario(cfg, setup: DiplomaRun):
    scenario = discover_scenario(
        cfg.scenario_dir,
        begin=0,
        end=max(setup.train_episode_seconds, setup.eval_seconds),
        step_length=cfg.step_length,
        auto_generate_sumocfg=True,
        auto_generate_pedestrians_if_missing=False,
        scenario_preferred_prefix=str(getattr(cfg, "scenario_preferred_prefix", "kaliningrad")),
    )
    if not scenario.found or not scenario.net:
        raise RuntimeError("В scenario/ не найден SUMO-сценарий с net.xml.")

    selected = select_tls_with_pedestrian_signals(Path(scenario.net), setup.controlled_tls)
    if not selected:
        raise RuntimeError("Не найдено TLS, где есть и автомобильные, и пешеходные controlled links.")

    demand_path = write_vehicle_demand(
        scenario.scenario_dir,
        Path(scenario.net),
        selected,
        setup.vehicle_count,
        begin=0,
        end=setup.eval_seconds,
    )
    cfg.scenario_route_file = demand_path.name
    cfg.allow_mixed_scenario_files = True
    cfg.scenario_sumocfg_file = None
    cfg.preferred_controlled_tls_ids = [item["tls_id"] for item in selected]
    cfg.max_controlled_tls = len(cfg.preferred_controlled_tls_ids)

    pedestrian_meta = {}
    if setup.pedestrian_count > 0:
        ok, message, _ = generate_pedestrian_demand(
            scenario_dir=scenario.scenario_dir,
            net=Path(scenario.net),
            count=setup.pedestrian_count,
            begin=0,
            end=setup.eval_seconds,
            prefix="auto_ped",
            pedestrian_mode="crossing_focused",
            preferred_controlled_tls_ids=cfg.preferred_controlled_tls_ids,
        )
        if not ok:
            raise RuntimeError(f"Не удалось создать пешеходный спрос: {message}")
        meta_path = scenario.scenario_dir / "autogenerated_pedestrians.meta.json"
        if meta_path.exists():
            pedestrian_meta = json.loads(meta_path.read_text(encoding="utf-8"))

    scenario = discover_scenario(
        cfg.scenario_dir,
        begin=0,
        end=max(setup.train_episode_seconds, setup.eval_seconds),
        step_length=cfg.step_length,
        auto_generate_sumocfg=True,
        scenario_route_file=demand_path.name,
        allow_mixed_scenario_files=True,
        auto_generate_pedestrians_if_missing=setup.pedestrian_count > 0,
        pedestrian_count=setup.pedestrian_count,
        pedestrian_begin=0,
        pedestrian_end=setup.eval_seconds,
        pedestrian_prefix="auto_ped",
        pedestrian_mode="crossing_focused",
        rl_use_real_timing_program_as_base=False,
        preferred_controlled_tls_ids=cfg.preferred_controlled_tls_ids,
    )
    return scenario, selected, pedestrian_meta


def select_tls_with_pedestrian_signals(net_path: Path, limit: int | None) -> list[dict]:
    add_sumo_tools_to_path()
    import sumolib

    net = sumolib.net.readNet(str(net_path), withPrograms=True, withConnections=True, withInternal=True)
    candidates = []
    for tls in net.getTrafficLights():
        vehicle_routes = []
        pedestrian_links = 0
        for conn in tls.getConnections():
            lanes = [item for item in conn[:2] if item is not None]
            if any(lane_allows_pedestrian(lane) and not lane_allows_vehicle(lane) for lane in lanes):
                pedestrian_links += 1
            if len(lanes) < 2:
                continue
            from_lane, to_lane = lanes[0], lanes[1]
            if not lane_allows_vehicle(from_lane) or not lane_allows_vehicle(to_lane):
                continue
            route = shortest_route_edges(net, from_lane, to_lane)
            if route and route not in vehicle_routes:
                vehicle_routes.append(route)
        if vehicle_routes and pedestrian_links > 0:
            candidates.append(
                {
                    "tls_id": str(tls.getID()),
                    "vehicle_pairs": vehicle_routes,
                    "pedestrian_signal_links": pedestrian_links,
                }
            )
    candidates.sort(key=lambda item: (item["pedestrian_signal_links"], len(item["vehicle_pairs"])), reverse=True)
    if limit is None:
        return candidates
    return candidates[: max(1, int(limit))]


def lane_allows_vehicle(lane) -> bool:
    for vehicle_class in ("passenger", "private", "bus", "truck", "taxi", "delivery"):
        try:
            if lane.allows(vehicle_class):
                return True
        except Exception:
            continue
    return False


def lane_allows_pedestrian(lane) -> bool:
    try:
        return bool(lane.allows("pedestrian"))
    except Exception:
        return False


def edge_id(lane) -> str:
    try:
        return str(lane.getEdge().getID())
    except Exception:
        return ""


def shortest_route_edges(net, from_lane, to_lane) -> list[str]:
    try:
        from_edge = from_lane.getEdge()
        to_edge = to_lane.getEdge()
        from_edge_id = str(from_edge.getID())
        to_edge_id = str(to_edge.getID())
    except Exception:
        return []
    if (
        not from_edge_id
        or not to_edge_id
        or from_edge_id == to_edge_id
        or from_edge_id.startswith(":")
        or to_edge_id.startswith(":")
    ):
        return []
    try:
        path, _ = net.getShortestPath(from_edge, to_edge)
    except Exception:
        path = None
    if not path:
        return []
    route = [str(edge.getID()) for edge in path if edge.getID() and not str(edge.getID()).startswith(":")]
    if len(route) < 2:
        return []
    return route


def write_vehicle_demand(
    scenario_dir: Path,
    net_path: Path,
    selected_tls: list[dict],
    count: int,
    begin: int,
    end: int,
) -> Path:
    output = Path(scenario_dir) / AUTOGENERATED_DIAGNOSTIC_DEMAND
    trips = Path(scenario_dir) / "autogenerated_diagnostic_trips.xml"
    end = max(begin + 1, int(end))
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<routes>",
    ]
    for idx in range(max(1, int(count))):
        tls = selected_tls[idx % len(selected_tls)]
        route = tls["vehicle_pairs"][idx % len(tls["vehicle_pairs"])]
        depart = begin + (end - begin) * idx / max(1, int(count) - 1)
        lines.append(
            f'    <trip id="car_{idx}" depart="{depart:.2f}" '
            f'from="{escape(route[0])}" to="{escape(route[-1])}"/>'
        )
    lines.append("</routes>")
    trips.write_text("\n".join(lines) + "\n", encoding="utf-8")
    duarouter = detect_duarouter()
    if not duarouter:
        raise RuntimeError("Не найден duarouter. Он нужен для построения валидных маршрутов машин.")
    result = subprocess.run(
        [
            duarouter,
            "-n",
            str(net_path),
            "-r",
            str(trips),
            "-o",
            str(output),
            "--ignore-errors",
            "true",
            "--no-warnings",
            "true",
        ],
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0 or not output.exists():
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "duarouter failed")
    return output


def detect_duarouter() -> str | None:
    sumo_home = os.environ.get("SUMO_HOME")
    if sumo_home:
        exe = "duarouter.exe" if os.name == "nt" else "duarouter"
        candidate = Path(sumo_home) / "bin" / exe
        if candidate.exists():
            return str(candidate)
    return None


def build_comparison(rl: dict, fixed: dict) -> dict:
    add_normalized_metrics(rl)
    add_normalized_metrics(fixed)
    rl_objective = objective_payload(rl).get("objective_score", 0.0)
    fixed_objective = objective_payload(fixed).get("objective_score", 0.0)
    vehicle_metrics = [
        "avg_queue",
        "avg_waiting_time",
        "avg_time_loss",
        "normalized_time_loss_per_departed",
        "total_waiting_time",
        "total_time_loss",
        "avg_speed",
        "arrived",
        "total_reward",
    ]
    pedestrian_metrics = ["avg_waiting_time", "total_waiting_time", "waiting_count"]
    vehicle = {
        metric: {"rl": rl.get(metric), "fixed": fixed.get(metric)}
        for metric in vehicle_metrics
        if metric != "arrived" or float(rl.get("arrived", 0) or 0) > 0 or float(fixed.get("arrived", 0) or 0) > 0
    }
    vehicle["objective_score"] = {"rl": rl_objective, "fixed": fixed_objective}
    return {
        "vehicle": vehicle,
        "pedestrian": {
            metric: {
                "rl": (rl.get("pedestrian_metrics") or {}).get(metric),
                "fixed": (fixed.get("pedestrian_metrics") or {}).get(metric),
            }
            for metric in pedestrian_metrics
        },
        "debug": {
            "throughput": {"rl": rl.get("throughput"), "fixed": fixed.get("throughput")},
            "arrived": {"rl": rl.get("arrived"), "fixed": fixed.get("arrived")},
            "pedestrian_departed": {
                "rl": (rl.get("pedestrian_metrics") or {}).get("departed"),
                "fixed": (fixed.get("pedestrian_metrics") or {}).get("departed"),
            },
            "pedestrian_arrived": {
                "rl": (rl.get("pedestrian_metrics") or {}).get("arrived"),
                "fixed": (fixed.get("pedestrian_metrics") or {}).get("arrived"),
            },
            "pedestrian_running": {
                "rl": (rl.get("pedestrian_metrics") or {}).get("running"),
                "fixed": (fixed.get("pedestrian_metrics") or {}).get("running"),
            },
        },
    }


def save_outputs(cfg, setup, selected_tls, pedestrian_meta, train_result, rl, fixed, comparison) -> None:
    payload = {
        "setup": asdict(setup),
        "controlled_tls": selected_tls,
        "pedestrian_metadata": pedestrian_meta,
        "train_result": train_result,
    }
    save_json(cfg.logs_dir / "run_config_resolved.json", payload)
    save_json(cfg.logs_dir / "comparison_rl_vs_fixed_native.json", comparison)
    write_csv_row(cfg.logs_dir / "comparison_rl_vs_fixed_native.csv", flatten_comparison(comparison))


def flatten_comparison(comparison: dict) -> dict:
    row = {}
    for section, metrics in comparison.items():
        if isinstance(metrics, dict):
            for metric, values in metrics.items():
                if isinstance(values, dict):
                    for side, value in values.items():
                        row[f"{section}_{metric}_{side}"] = value
    return row


def print_summary(setup: DiplomaRun, scenario, selected_tls: list[dict], pedestrian_meta: dict) -> None:
    print()
    print(f"Selected mode: {setup.mode}")
    print(f"Training: {setup.train_episodes} x {setup.train_episode_seconds} sec")
    print(f"Evaluation: {setup.eval_seconds} sec")
    print(f"TLS controlled: {len(selected_tls)}")
    print(f"Vehicles: {setup.vehicle_count}")
    print(f"Pedestrians: {'yes' if setup.pedestrian_count > 0 else 'no'}, {setup.pedestrian_count}")
    print(f"Pedestrian signal links: {sum(item['pedestrian_signal_links'] for item in selected_tls)}")
    print(f"Device: {setup.device}")
    print()
    print("Scenario")
    print("--------")
    print(f"net: {Path(scenario.net).name if scenario.net else '-'}")
    print(f"routes: {', '.join(Path(path).name for path in scenario.route_files)}")
    if pedestrian_meta.get("warning"):
        print(f"WARNING: {pedestrian_meta['warning']}")


def print_comparison(comparison: dict) -> None:
    print_table("Сравнение таймингов модели vs fixed-time для машин", comparison["vehicle"])
    print_table("Сравнение таймингов модели vs fixed-time для пешеходов", comparison["pedestrian"])


def print_table(title: str, metrics: dict) -> None:
    print()
    print(title)
    print("-" * len(title))
    metric_width = max(34, max((len(key) for key in metrics), default=0))
    value_width = 14
    print(f"{'Метрика':<{metric_width}}  {'Модель':>{value_width}}  {'fixed-time':>{value_width}}")
    print(f"{'-' * metric_width}  {'-' * value_width}  {'-' * value_width}")
    for metric, values in metrics.items():
        print(f"{metric:<{metric_width}}  {format_value(values.get('rl')):>{value_width}}  {format_value(values.get('fixed')):>{value_width}}")


def format_value(value) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.4f}"
    return str(value)


def print_action_diagnostics(rl: dict, fixed: dict) -> None:
    rl_actions = rl.get("action_stats") or {}
    fixed_actions = fixed.get("baseline_stats") or fixed.get("action_stats") or {}
    print()
    print("RL action diagnostics")
    print("---------------------")
    print(f"decisions: {rl_actions.get('decision_count', 0)}")
    print(f"switches: {rl_actions.get('switch_count', 0)}")
    print(f"phase_set: {rl_actions.get('phase_set_count', 0)}")
    print(f"fixed_phase_set: {fixed_actions.get('phase_set_count', 0)}")


def print_runtime(started: float, train_result: dict) -> None:
    print()
    print("Runtime")
    print("-------")
    print(f"total_seconds: {time.perf_counter() - started:.1f}")
    print(f"optimizer_steps: {train_result.get('optimizer_steps', 0)}")


def validate_result(rl: dict, fixed: dict, comparison: dict, pedestrian_meta: dict) -> int:
    failures = []
    rl_actions = rl.get("action_stats") or {}
    fixed_actions = fixed.get("baseline_stats") or fixed.get("action_stats") or {}
    if int(rl_actions.get("decision_count", 0) or 0) <= 0:
        failures.append("RL не принимал решений.")
    if int(rl_actions.get("phase_set_count", 0) or 0) <= 0:
        failures.append("RL не вызвал traci.trafficlight.setPhase.")
    if int(fixed_actions.get("phase_set_count", 0) or 0) != 0:
        failures.append("fixed-time baseline вручную менял фазы.")
    if int(pedestrian_meta.get("pedestrian_signal_link_count", 0) or 0) <= 0:
        failures.append("Выбранные TLS не имеют pedestrian signal links.")
    if not metrics_nonzero_and_different(comparison["vehicle"]):
        failures.append("Автомобильные primary metrics нулевые или полностью одинаковые.")
    if not metrics_nonzero_and_different(comparison["pedestrian"]):
        failures.append("Пешеходные metrics нулевые или полностью одинаковые.")
    if failures:
        print()
        print("Validation warnings")
        print("-------------------")
        for item in failures:
            print(f"WARNING: {item}")
    return 1 if failures else 0


def metrics_nonzero_and_different(metrics: dict) -> bool:
    pairs = []
    for values in metrics.values():
        try:
            rl = float(values.get("rl") or 0.0)
            fixed = float(values.get("fixed") or 0.0)
        except (TypeError, ValueError):
            continue
        pairs.append((rl, fixed))
    if not pairs:
        return False
    nonzero = any(abs(rl) > 1e-9 or abs(fixed) > 1e-9 for rl, fixed in pairs)
    different = any(abs(rl - fixed) > 1e-6 for rl, fixed in pairs)
    return nonzero and different


def _configure_console() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")
