import copy
import json
import os
import subprocess
import uuid
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Set, Tuple
from xml.sax.saxutils import escape

from .utils import add_sumo_tools_to_path, detect_sumo_cmd


AUTOGENERATED_SUMOCFG = "autogenerated.sumocfg"
AUTOGENERATED_NATIVE_SUMOCFG = "autogenerated_native.sumocfg"
AUTOGENERATED_REAL_TIMING_SUMOCFG = "autogenerated_real_timing.sumocfg"
AUTOGENERATED_RL_SUMOCFG = "autogenerated_rl.sumocfg"
AUTOGENERATED_PEDESTRIANS = "autogenerated_pedestrians.rou.xml"
AUTOGENERATED_PEDESTRIANS_META = "autogenerated_pedestrians.meta.json"
AUTOGENERATED_DIAGNOSTIC_DEMAND = "autogenerated_diagnostic_demand.rou.xml"
AUTOGENERATED_FILTERED_TIMING = "autogenerated_real_timing_filtered.add.xml"


def _skip_pedestrian_route_smoke_test() -> bool:
    return os.environ.get("BFU_SKIP_PED_ROUTE_SMOKE_TEST", "").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }

VEHICLE_CLASSES = {
    "passenger",
    "private",
    "taxi",
    "bus",
    "coach",
    "delivery",
    "truck",
    "trailer",
    "motorcycle",
    "moped",
    "bicycle",
    "evehicle",
    "emergency",
    "authority",
    "army",
    "vip",
    "hov",
    "custom1",
    "custom2",
}

ROUTE_TAGS = {
    "routes",
    "route",
    "routeDistribution",
    "routes",
    "vehicle",
    "trip",
    "flow",
    "person",
    "personFlow",
    "walk",
    "ride",
    "vType",
    "vTypeDistribution",
}

PERSON_TAGS = {"person", "personFlow", "walk"}
TIMING_TAGS = {"tlLogic"}

ADDITIONAL_TAGS = {
    "additional",
    "poly",
    "poi",
    "busStop",
    "trainStop",
    "containerStop",
    "parkingArea",
    "chargingStation",
    "inductionLoop",
    "laneAreaDetector",
    "instantInductionLoop",
    "multiEntryExitDetector",
    "entryExitDetector",
    "e1Detector",
    "e2Detector",
    "e3Detector",
    "calibrator",
    "rerouter",
    "routeProbe",
    "variableSpeedSign",
    "detector",
}


@dataclass
class ScenarioFiles:
    scenario_dir: Path
    sumocfg: Optional[Path] = None
    net: Optional[Path] = None
    route_files: List[Path] = field(default_factory=list)
    additional_files: List[Path] = field(default_factory=list)
    timing_files: List[Path] = field(default_factory=list)
    real_timing_file: Optional[Path] = None
    mode_sumocfgs: dict = field(default_factory=dict)
    autogenerated: bool = False
    found: bool = False
    source: str = "none"
    notes: List[str] = field(default_factory=list)
    pedestrian_existing_found: bool = False
    pedestrian_autogenerated: bool = False
    pedestrian_route_file: Optional[Path] = None
    pedestrian_count: int = 0
    pedestrian_mode: str = "random_walks"
    pedestrian_tls_sensitive_routes: int = 0
    pedestrian_route_warning: str = ""
    pedestrian_metadata: dict = field(default_factory=dict)
    osm_file: Optional[Path] = None
    scenario_prefix: str = ""
    timing_matching_tls: List[str] = field(default_factory=list)
    timing_missing_tls: List[str] = field(default_factory=list)
    timing_filtered_file: Optional[Path] = None

    @property
    def primary_route(self) -> Optional[Path]:
        return self.route_files[0] if self.route_files else None

    @property
    def primary_additional(self) -> Optional[Path]:
        return self.additional_files[0] if self.additional_files else None

    def as_legacy_dict(self) -> dict:
        return {
            "sumocfg": self.sumocfg,
            "net": self.net,
            "rou": self.primary_route,
            "add": self.primary_additional,
            "route_files": list(self.route_files),
            "additional_files": list(self.additional_files),
            "timing_files": list(self.timing_files),
            "real_timing_file": self.real_timing_file,
            "found": self.found,
        }

    def sumocfg_for_mode(self, mode: str) -> Optional[Path]:
        normalized = normalize_sumo_mode(mode)
        return self.mode_sumocfgs.get(normalized) or self.sumocfg


def normalize_sumo_mode(mode: str) -> str:
    if mode == "fixed":
        return "fixed_native"
    return str(mode or "fixed_native")


def discover_scenario(
    scenario_dir: Path,
    begin: float = 0.0,
    end: float = 300.0,
    step_length: float = 1.0,
    auto_generate_sumocfg: bool = True,
    scenario_sumocfg_file: Optional[Path] = None,
    scenario_net_file: Optional[Path] = None,
    scenario_route_file: Optional[Path] = None,
    auto_generate_pedestrians_if_missing: bool = False,
    pedestrian_count: int = 30,
    pedestrian_begin: int = 0,
    pedestrian_end: int = 300,
    pedestrian_prefix: str = "auto_ped",
    pedestrian_mode: str = "random_walks",
    real_timing_file_name: str = "tls.add.xml",
    rl_use_real_timing_program_as_base: bool = True,
    scenario_preferred_prefix: str = "kaliningrad",
    allow_mixed_scenario_files: bool = False,
    preferred_controlled_tls_ids: Optional[Sequence[str]] = None,
) -> ScenarioFiles:
    scenario_dir = Path(scenario_dir)
    scenario_dir.mkdir(parents=True, exist_ok=True)

    explicit_sumocfg = _resolve_optional_path(scenario_dir, scenario_sumocfg_file)
    if explicit_sumocfg and explicit_sumocfg.exists():
        scenario = _scenario_from_sumocfg(scenario_dir, explicit_sumocfg, source="explicit_sumocfg")
        return _finalize_scenario(
            scenario,
            begin,
            end,
            step_length,
            auto_generate_sumocfg,
            auto_generate_pedestrians_if_missing,
            pedestrian_count,
            pedestrian_begin,
            pedestrian_end,
            pedestrian_prefix,
            pedestrian_mode,
            real_timing_file_name,
            rl_use_real_timing_program_as_base,
            preferred_controlled_tls_ids,
        )

    net = _select_net_file(scenario_dir, scenario_net_file, scenario_preferred_prefix)
    explicit_route = _resolve_optional_path(scenario_dir, scenario_route_file)
    explicit_route_selected = bool(explicit_route and explicit_route.exists())
    route_files = [
        path
        for path in _select_route_files(
            scenario_dir,
            scenario_route_file,
            selected_net=net,
            preferred_prefix=scenario_preferred_prefix,
            allow_mixed_scenario_files=allow_mixed_scenario_files,
        )
        if path.name != AUTOGENERATED_PEDESTRIANS
    ]
    if not net or not route_files:
        user_sumocfgs = [
            path
            for path in sorted(scenario_dir.glob("*.sumocfg"))
            if path.name.lower()
            not in {
                AUTOGENERATED_SUMOCFG,
                AUTOGENERATED_NATIVE_SUMOCFG,
                AUTOGENERATED_REAL_TIMING_SUMOCFG,
                AUTOGENERATED_RL_SUMOCFG,
            }
        ]
        if user_sumocfgs:
            scenario = _scenario_from_sumocfg(scenario_dir, user_sumocfgs[0], source="sumocfg")
            return _finalize_scenario(
                scenario,
                begin,
                end,
                step_length,
                auto_generate_sumocfg,
                auto_generate_pedestrians_if_missing,
                pedestrian_count,
                pedestrian_begin,
                pedestrian_end,
                pedestrian_prefix,
                pedestrian_mode,
                real_timing_file_name,
                rl_use_real_timing_program_as_base,
                preferred_controlled_tls_ids,
            )
        generated = scenario_dir / AUTOGENERATED_SUMOCFG
        if generated.exists():
            parsed = _scenario_from_sumocfg(scenario_dir, generated, source="autogenerated_sumocfg")
            if parsed.net and parsed.route_files:
                return _finalize_scenario(
                    parsed,
                    begin,
                    end,
                    step_length,
                    auto_generate_sumocfg,
                    auto_generate_pedestrians_if_missing,
                    pedestrian_count,
                    pedestrian_begin,
                    pedestrian_end,
                    pedestrian_prefix,
                    pedestrian_mode,
                    real_timing_file_name,
                    rl_use_real_timing_program_as_base,
                    preferred_controlled_tls_ids,
                )
        return ScenarioFiles(scenario_dir=scenario_dir, found=False)

    scenario_prefix = _net_prefix(net)
    strict_prefix_routes = (
        bool(scenario_prefix)
        and bool(scenario_preferred_prefix)
        and scenario_prefix.lower() == str(scenario_preferred_prefix).lower()
        and not bool(allow_mixed_scenario_files)
    )
    route_files, additional_files, timing_files, notes = _classify_companion_xml(
        scenario_dir,
        net,
        route_files,
        scenario_prefix=scenario_prefix if strict_prefix_routes else "",
        allow_mixed_scenario_files=allow_mixed_scenario_files,
        include_companion_routes=not explicit_route_selected,
    )
    scenario = ScenarioFiles(
        scenario_dir=scenario_dir,
        net=net,
        route_files=route_files,
        additional_files=additional_files,
        timing_files=timing_files,
        found=True,
        source="net_and_routes",
        notes=notes,
        scenario_prefix=scenario_prefix,
        osm_file=_select_osm_file(scenario_dir, scenario_prefix),
    )
    return _finalize_scenario(
        scenario,
        begin,
        end,
        step_length,
        auto_generate_sumocfg,
        auto_generate_pedestrians_if_missing,
        pedestrian_count,
        pedestrian_begin,
        pedestrian_end,
        pedestrian_prefix,
        pedestrian_mode,
        real_timing_file_name,
        rl_use_real_timing_program_as_base,
        preferred_controlled_tls_ids,
    )


def _finalize_scenario(
    scenario: ScenarioFiles,
    begin: float,
    end: float,
    step_length: float,
    auto_generate_sumocfg: bool,
    auto_generate_pedestrians_if_missing: bool,
    pedestrian_count: int,
    pedestrian_begin: int,
    pedestrian_end: int,
    pedestrian_prefix: str,
    pedestrian_mode: str,
    real_timing_file_name: str,
    rl_use_real_timing_program_as_base: bool,
    preferred_controlled_tls_ids: Optional[Sequence[str]] = None,
) -> ScenarioFiles:
    if not scenario.found:
        return scenario
    scenario.pedestrian_mode = str(pedestrian_mode or "random_walks").strip().lower()
    preferred_tls_ids = _normalize_tls_ids(preferred_controlled_tls_ids)

    if scenario.net and not scenario.scenario_prefix:
        scenario.scenario_prefix = _net_prefix(scenario.net)
    if scenario.osm_file is None:
        scenario.osm_file = _select_osm_file(scenario.scenario_dir, scenario.scenario_prefix)

    ordinary, timing = _split_timing_files(scenario.additional_files)
    scenario.additional_files = ordinary
    scenario.timing_files = _unique_paths([*scenario.timing_files, *timing])
    named_timing = scenario.scenario_dir / str(real_timing_file_name)
    if named_timing.exists() and named_timing not in scenario.timing_files:
        kind, _ = _classify_xml(named_timing)
        if kind == "timing":
            scenario.timing_files.append(named_timing)
    scenario.timing_files = _unique_paths(scenario.timing_files)
    scenario.real_timing_file = _select_real_timing_file(scenario.timing_files, real_timing_file_name)
    scenario.real_timing_file = _prepare_real_timing_file(scenario)

    scenario.route_files = [path for path in scenario.route_files if path.name != AUTOGENERATED_PEDESTRIANS]
    scenario.pedestrian_existing_found = route_files_have_pedestrians(scenario.route_files)
    generated_pedestrians = scenario.scenario_dir / AUTOGENERATED_PEDESTRIANS
    if (
        generated_pedestrians.exists()
        and preferred_tls_ids
        and auto_generate_pedestrians_if_missing
        and scenario.pedestrian_mode == "crossing_focused"
    ):
        metadata = _load_autogenerated_pedestrian_metadata(scenario.scenario_dir)
        if not _pedestrian_metadata_matches_preferred_tls(metadata, preferred_tls_ids):
            scenario.notes.append(
                "Existing autogenerated_pedestrians.rou.xml does not target the selected controlled TLS; regenerating."
            )
            try:
                generated_pedestrians.unlink(missing_ok=True)
                (scenario.scenario_dir / AUTOGENERATED_PEDESTRIANS_META).unlink(missing_ok=True)
            except Exception:
                pass
    if (
        scenario.net
        and not scenario.pedestrian_existing_found
        and generated_pedestrians.exists()
    ):
        if _skip_pedestrian_route_smoke_test():
            ok, message = True, "pedestrian route smoke-test skipped"
        else:
            ok, message = _smoke_test_pedestrian_file(scenario.scenario_dir, scenario.net, generated_pedestrians)
        if ok:
            scenario.route_files.append(generated_pedestrians)
            scenario.pedestrian_route_file = generated_pedestrians
            scenario.pedestrian_count = _count_persons(generated_pedestrians)
            scenario.pedestrian_metadata = _load_autogenerated_pedestrian_metadata(scenario.scenario_dir)
            scenario.pedestrian_tls_sensitive_routes = int(
                scenario.pedestrian_metadata.get("tls_sensitive_routes", 0) or 0
            )
            scenario.pedestrian_route_warning = str(
                scenario.pedestrian_metadata.get("warning", "") or ""
            )
            scenario.notes.append("Using existing autogenerated_pedestrians.rou.xml.")
        else:
            scenario.notes.append(
                "Existing autogenerated_pedestrians.rou.xml is incompatible with the selected net-file "
                f"and will be regenerated if enabled: {message}"
            )
            try:
                generated_pedestrians.unlink(missing_ok=True)
            except Exception:
                pass

    if (
        scenario.net
        and not scenario.pedestrian_existing_found
        and scenario.pedestrian_route_file is None
        and auto_generate_pedestrians_if_missing
    ):
        ok, message, generated = generate_pedestrian_demand(
            scenario_dir=scenario.scenario_dir,
            net=scenario.net,
            count=pedestrian_count,
            begin=pedestrian_begin,
            end=pedestrian_end,
            prefix=pedestrian_prefix,
            pedestrian_mode=scenario.pedestrian_mode,
            preferred_controlled_tls_ids=preferred_tls_ids,
        )
        if ok and generated:
            scenario.route_files.append(generated)
            scenario.pedestrian_autogenerated = True
            scenario.pedestrian_route_file = generated
            scenario.pedestrian_count = _count_persons(generated)
            scenario.pedestrian_metadata = _load_autogenerated_pedestrian_metadata(scenario.scenario_dir)
            scenario.pedestrian_tls_sensitive_routes = int(
                scenario.pedestrian_metadata.get("tls_sensitive_routes", 0) or 0
            )
            scenario.pedestrian_route_warning = str(
                scenario.pedestrian_metadata.get("warning", "") or ""
            )
            scenario.notes.append("Пешеходы не найдены. Создан autogenerated_pedestrians.rou.xml для dev-проверки.")
            if scenario.pedestrian_route_warning:
                scenario.notes.append(scenario.pedestrian_route_warning)
        else:
            scenario.notes.append(message)
    if auto_generate_sumocfg:
        scenario.autogenerated = True
        write_mode_sumocfgs(
            scenario,
            begin=begin,
            end=end,
            step_length=step_length,
            rl_use_real_timing_program_as_base=rl_use_real_timing_program_as_base,
        )
    return scenario


def route_files_have_pedestrians(route_files: Sequence[Path]) -> bool:
    for path in route_files:
        try:
            _, tags = _classify_xml(Path(path))
            if PERSON_TAGS.intersection(tags):
                return True
        except Exception:
            continue
    return False


def generate_pedestrian_demand(
    scenario_dir: Path,
    net: Path,
    count: int,
    begin: int,
    end: int,
    prefix: str,
    pedestrian_mode: str = "random_walks",
    preferred_controlled_tls_ids: Optional[Sequence[str]] = None,
) -> Tuple[bool, str, Optional[Path]]:
    scenario_dir = Path(scenario_dir)
    output = scenario_dir / AUTOGENERATED_PEDESTRIANS
    meta_path = scenario_dir / AUTOGENERATED_PEDESTRIANS_META
    mode = str(pedestrian_mode or "random_walks").strip().lower()
    preferred_tls_ids = _normalize_tls_ids(preferred_controlled_tls_ids)
    if mode == "existing_persons":
        _write_pedestrian_metadata(
            meta_path,
            {
                "pedestrian_mode": mode,
                "requested_count": int(count),
                "actual_persons": 0,
                "tls_sensitive_routes": 0,
                "warning": "Pedestrian mode existing_persons requested, but no existing persons were found.",
            },
        )
        return False, "Pedestrian mode existing_persons requested, but no existing persons were found.", None
    try:
        add_sumo_tools_to_path()
        import sumolib

        sumo_net = sumolib.net.readNet(str(net), withInternal=True)
        edges = []
        edge_nodes = {}
        for edge in sumo_net.getEdges():
            edge_id = edge.getID()
            if edge_id.startswith(":"):
                continue
            try:
                if edge.allows("pedestrian"):
                    edges.append(edge_id)
                    edge_nodes[edge_id] = _edge_node_pair(edge)
                    continue
            except Exception:
                pass
            try:
                if any(lane.allows("pedestrian") for lane in edge.getLanes()):
                    edges.append(edge_id)
                    edge_nodes[edge_id] = _edge_node_pair(edge)
            except Exception:
                continue
    except Exception as exc:
        return False, f"Could not generate pedestrian routes: {exc}", None

    if not edges:
        return False, "Could not generate pedestrian routes: no pedestrian-compatible edges found.", None

    edges = sorted(dict.fromkeys(edges))
    demand_count = max(0, int(count))
    begin = int(begin)
    end = max(begin + 1, int(end))

    warning = ""
    pairs = []
    tls_sensitive_edges: list[str] = []
    controlled_tls_edges: list[str] = []
    controlled_tls_sensitive_count = 0
    pair_source = "all_pedestrian_edges"
    tls_diagnostics: dict = {
        "preferred_controlled_tls_ids": preferred_tls_ids,
        "controlled_tls_ids": [],
        "controlled_tls_overlap_count": 0,
        "controlled_tls_overlap_edges": [],
        "controlled_tls_edges_by_tls": {},
    }
    if mode == "crossing_focused":
        if preferred_tls_ids:
            (
                pairs,
                controlled_tls_edges,
                tls_diagnostics,
                warning,
            ) = _controlled_tls_pedestrian_pairs(
                net=Path(net),
                pedestrian_edges=edges,
                edge_nodes=edge_nodes,
                preferred_tls_ids=preferred_tls_ids,
            )
            if pairs:
                tls_sensitive_edges = list(controlled_tls_edges)
                controlled_tls_sensitive_count = demand_count
                pair_source = "preferred_controlled_tls"
                if int(tls_diagnostics.get("pedestrian_signal_link_count", 0) or 0) <= 0:
                    warning = (
                        "Selected controlled TLS do not expose pedestrian signal links in net.xml; "
                        "pedestrian timing metrics may match fixed-time even when vehicle phases change."
                    )
        if not pairs:
            fallback_warning = ""
            pairs, tls_sensitive_edges, fallback_warning = _tls_sensitive_pedestrian_pairs(
                net=Path(net),
                pedestrian_edges=edges,
                edge_nodes=edge_nodes,
            )
            pair_source = "global_tls"
            if preferred_tls_ids:
                warning = (
                    warning
                    or fallback_warning
                    or "Could not generate pedestrian routes on selected controlled TLS; using global TLS-sensitive routes."
                )
                tls_diagnostics["fallback_to_global_tls"] = True
            else:
                warning = fallback_warning
        if not pairs:
            warning = warning or "Could not generate TLS-sensitive pedestrian routes; pedestrian metrics may be identical."
    if not pairs:
        shift = max(1, len(edges) // 2)
        pairs = [(edges[idx % len(edges)], edges[(idx + shift) % len(edges)]) for idx in range(max(1, len(edges)))]
        pair_source = "all_pedestrian_edges"

    person_ids = [f"{prefix}_{idx}" for idx in range(demand_count)]
    _write_pedestrian_routes(output, pairs, demand_count, begin, end, prefix)
    tls_sensitive_count = demand_count if mode == "crossing_focused" and tls_sensitive_edges else 0
    controlled_tls_sensitive_person_ids = person_ids if controlled_tls_sensitive_count else []
    _write_pedestrian_metadata(
        meta_path,
        {
            "pedestrian_mode": mode,
            "requested_count": int(count),
            "actual_persons": demand_count,
            "depart_window": f"{begin}..{end}",
            "tls_sensitive_routes": tls_sensitive_count,
            "controlled_tls_sensitive_routes": controlled_tls_sensitive_count,
            "warning": warning,
            "route_file": output.name,
            "person_ids": person_ids,
            "tls_sensitive_person_ids": person_ids if tls_sensitive_count else [],
            "controlled_tls_sensitive_person_ids": controlled_tls_sensitive_person_ids,
            "tls_sensitive_edges": list(tls_sensitive_edges)[:200],
            "controlled_tls_overlap_edges": list(controlled_tls_edges)[:200],
            "controlled_tls_overlap_count": len(controlled_tls_edges),
            "preferred_controlled_tls_ids": preferred_tls_ids,
            "controlled_tls_ids": list(tls_diagnostics.get("controlled_tls_ids", [])),
            "controlled_tls_edges_by_tls": {
                str(tls_id): list(values)[:50]
                for tls_id, values in (tls_diagnostics.get("controlled_tls_edges_by_tls", {}) or {}).items()
            },
            "controlled_lane_overlap_edges": list(tls_diagnostics.get("controlled_lane_overlap_edges", []) or [])[:200],
            "controlled_tls_junctions": list(tls_diagnostics.get("controlled_tls_junctions", []) or [])[:200],
            "pedestrian_signal_link_count": int(tls_diagnostics.get("pedestrian_signal_link_count", 0) or 0),
            "pedestrian_signal_links_by_tls": {
                str(tls_id): int(count)
                for tls_id, count in (tls_diagnostics.get("pedestrian_signal_links_by_tls", {}) or {}).items()
            },
            "pedestrian_pair_source": pair_source,
            "walk_pairs_sample": [
                {"from": str(from_edge), "to": str(to_edge)}
                for from_edge, to_edge in list(pairs)[:20]
            ],
            "pedestrian_edges_sample": list(edges)[:20],
        },
    )
    if _skip_pedestrian_route_smoke_test():
        return True, "", output
    ok, message = _smoke_test_pedestrian_file(scenario_dir, net, output)
    if ok:
        return True, "", output

    # Fallback: same-edge walks are accepted by SUMO on networks where cross-edge
    # pedestrian routing is not available.
    fallback_warning = (
        "Could not generate TLS-sensitive pedestrian routes; pedestrian metrics may be identical. "
        f"Original pedestrian route smoke-test failed: {message}"
    )
    fallback_pairs = [(edge, edge) for edge in edges]
    _write_pedestrian_routes(output, fallback_pairs, demand_count, begin, end, prefix)
    _write_pedestrian_metadata(
        meta_path,
        {
            "pedestrian_mode": mode,
            "requested_count": int(count),
            "actual_persons": demand_count,
            "depart_window": f"{begin}..{end}",
            "tls_sensitive_routes": 0,
            "controlled_tls_sensitive_routes": 0,
            "warning": fallback_warning,
            "route_file": output.name,
            "person_ids": person_ids,
            "tls_sensitive_person_ids": [],
            "controlled_tls_sensitive_person_ids": [],
            "tls_sensitive_edges": [],
            "controlled_tls_overlap_edges": [],
            "controlled_tls_overlap_count": 0,
            "preferred_controlled_tls_ids": preferred_tls_ids,
            "controlled_tls_ids": [],
            "controlled_tls_edges_by_tls": {},
            "controlled_lane_overlap_edges": [],
            "controlled_tls_junctions": [],
            "pedestrian_signal_link_count": 0,
            "pedestrian_signal_links_by_tls": {},
            "pedestrian_pair_source": "same_edge_fallback",
            "pedestrian_edges_sample": list(edges)[:20],
        },
    )
    ok, fallback_message = _smoke_test_pedestrian_file(scenario_dir, net, output)
    if ok:
        return True, "", output
    return False, f"Could not generate pedestrian routes: {message}; fallback failed: {fallback_message}", None


def _write_pedestrian_routes(
    output: Path,
    pairs: Sequence[tuple[str, str]],
    demand_count: int,
    begin: int,
    end: int,
    prefix: str,
) -> None:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<routes>"]
    for idx in range(max(0, int(demand_count))):
        depart = begin + int((end - begin) * idx / max(1, demand_count))
        from_edge, to_edge = pairs[idx % len(pairs)]
        lines.append(f'    <person id="{prefix}_{idx}" depart="{depart}">')
        lines.append(f'        <walk from="{escape(str(from_edge))}" to="{escape(str(to_edge))}"/>')
        lines.append("    </person>")
    lines.append("</routes>")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _edge_node_pair(edge) -> tuple[str, str]:
    try:
        from_node = edge.getFromNode().getID()
    except Exception:
        from_node = ""
    try:
        to_node = edge.getToNode().getID()
    except Exception:
        to_node = ""
    return str(from_node), str(to_node)


def _normalize_tls_ids(tls_ids: Optional[Sequence[str]]) -> list[str]:
    result = []
    for tls_id in tls_ids or []:
        text = str(tls_id).strip()
        if text and text not in result:
            result.append(text)
    return result


def _pedestrian_metadata_matches_preferred_tls(metadata: dict, preferred_tls_ids: Sequence[str]) -> bool:
    preferred = set(_normalize_tls_ids(preferred_tls_ids))
    if not preferred:
        return True
    configured = set(_normalize_tls_ids(metadata.get("controlled_tls_ids") or []))
    overlap_count = int(metadata.get("controlled_tls_overlap_count", 0) or 0)
    sensitive_routes = int(metadata.get("controlled_tls_sensitive_routes", 0) or 0)
    return bool(configured.intersection(preferred) and overlap_count > 0 and sensitive_routes > 0)


def _controlled_tls_pedestrian_pairs(
    net: Path,
    pedestrian_edges: Sequence[str],
    edge_nodes: dict,
    preferred_tls_ids: Sequence[str],
) -> tuple[list[tuple[str, str]], list[str], dict, str]:
    preferred = _normalize_tls_ids(preferred_tls_ids)
    diagnostics = {
        "preferred_controlled_tls_ids": preferred,
        "controlled_tls_ids": [],
        "controlled_tls_overlap_count": 0,
        "controlled_tls_overlap_edges": [],
        "controlled_tls_edges_by_tls": {},
        "controlled_lane_overlap_edges": [],
        "controlled_tls_junctions": [],
        "pedestrian_signal_link_count": 0,
        "pedestrian_signal_links_by_tls": {},
    }
    if not preferred:
        return [], [], diagnostics, ""

    try:
        add_sumo_tools_to_path()
        import sumolib

        sumo_net = sumolib.net.readNet(str(net), withPrograms=True, withConnections=True, withInternal=True)
    except Exception as exc:
        return [], [], diagnostics, f"Could not inspect selected controlled TLS for pedestrians: {exc}"

    pedestrian_edge_set = set(str(edge_id) for edge_id in pedestrian_edges)
    tls_by_id = {str(tls.getID()): tls for tls in sumo_net.getTrafficLights()}
    traffic_light_junctions = _tls_junction_ids(net)
    selected_junctions_by_tls: dict[str, list[str]] = {}
    pedestrian_signal_links_by_tls: dict[str, int] = {}
    lane_overlap_edges: set[str] = set()
    missing_tls = []

    for tls_id in preferred:
        tls = tls_by_id.get(tls_id)
        if tls is None:
            missing_tls.append(tls_id)
            continue
        controlled_edges = set()
        selected_junctions = set()
        for conn in tls.getConnections():
            lanes = _connection_lanes(conn)
            if _connection_has_pedestrian_signal_lane(conn):
                pedestrian_signal_links_by_tls[tls_id] = pedestrian_signal_links_by_tls.get(tls_id, 0) + 1
            for lane in lanes:
                edge_id = _lane_edge_id(lane)
                if edge_id and not edge_id.startswith(":"):
                    controlled_edges.add(edge_id)
            selected_junctions.update(_connection_junction_ids(conn, traffic_light_junctions))
        lane_overlap_edges.update(edge_id for edge_id in controlled_edges if edge_id in pedestrian_edge_set)
        if selected_junctions:
            selected_junctions_by_tls[tls_id] = sorted(selected_junctions)

    junction_to_tls: dict[str, str] = {}
    for tls_id, junctions in selected_junctions_by_tls.items():
        for junction_id in junctions:
            junction_to_tls.setdefault(junction_id, tls_id)

    by_junction: dict[str, list[str]] = {junction: [] for junction in junction_to_tls}
    for edge_id in pedestrian_edges:
        from_node, to_node = edge_nodes.get(edge_id, ("", ""))
        for node_id in (from_node, to_node):
            if node_id in by_junction:
                by_junction[node_id].append(edge_id)

    pairs: list[tuple[str, str]] = []
    sensitive_edges: set[str] = set()
    edges_by_tls: dict[str, list[str]] = {}
    for junction_id in sorted(by_junction):
        node_edges = sorted(dict.fromkeys(by_junction[junction_id]))
        if len(node_edges) < 2:
            continue
        tls_id = junction_to_tls.get(junction_id, "")
        if tls_id:
            current = edges_by_tls.setdefault(tls_id, [])
            for edge_id in node_edges:
                if edge_id not in current:
                    current.append(edge_id)
        half = max(1, len(node_edges) // 2)
        for idx, from_edge in enumerate(node_edges):
            to_edge = node_edges[(idx + half) % len(node_edges)]
            if from_edge == to_edge:
                continue
            pairs.append((from_edge, to_edge))
            sensitive_edges.add(from_edge)
            sensitive_edges.add(to_edge)

    if not pairs and lane_overlap_edges:
        lane_edges = sorted(lane_overlap_edges)
        for tls_id in preferred:
            tls_edges = [edge_id for edge_id in lane_edges if edge_id in lane_overlap_edges]
            if len(tls_edges) < 2:
                continue
            half = max(1, len(tls_edges) // 2)
            for idx, from_edge in enumerate(tls_edges):
                to_edge = tls_edges[(idx + half) % len(tls_edges)]
                if from_edge == to_edge:
                    continue
                pairs.append((from_edge, to_edge))
                sensitive_edges.add(from_edge)
                sensitive_edges.add(to_edge)
            if pairs:
                edges_by_tls[tls_id] = tls_edges
                break

    diagnostics.update(
        {
            "controlled_tls_ids": list(edges_by_tls.keys()),
            "controlled_tls_overlap_count": len(sensitive_edges),
            "controlled_tls_overlap_edges": sorted(sensitive_edges)[:200],
            "controlled_tls_edges_by_tls": edges_by_tls,
            "controlled_lane_overlap_edges": sorted(lane_overlap_edges)[:200],
            "controlled_tls_junctions": sorted(junction_to_tls.keys())[:200],
            "pedestrian_signal_link_count": sum(pedestrian_signal_links_by_tls.values()),
            "pedestrian_signal_links_by_tls": pedestrian_signal_links_by_tls,
            "missing_tls_ids": missing_tls,
        }
    )
    if not pairs:
        return (
            [],
            [],
            diagnostics,
            "Could not generate pedestrian routes on selected controlled TLS; pedestrian metrics may be identical.",
        )
    return pairs, sorted(sensitive_edges), diagnostics, ""


def _connection_lanes(conn) -> list:
    lanes = []
    try:
        if isinstance(conn, (list, tuple)):
            lanes.extend([item for item in conn[:2] if item is not None])
            return lanes
    except Exception:
        pass
    for method_name in ("getFromLane", "getToLane"):
        try:
            lane = getattr(conn, method_name)()
            if lane is not None:
                lanes.append(lane)
        except Exception:
            continue
    return lanes


def _connection_junction_ids(conn, traffic_light_junctions: set[str]) -> set[str]:
    junctions = set()
    lanes = _connection_lanes(conn)
    for index, lane in enumerate(lanes[:2]):
        try:
            edge = lane.getEdge()
        except Exception:
            continue
        node_candidates = []
        try:
            if index == 0:
                node_candidates.append(edge.getToNode().getID())
            else:
                node_candidates.append(edge.getFromNode().getID())
        except Exception:
            pass
        try:
            node_candidates.extend([edge.getFromNode().getID(), edge.getToNode().getID()])
        except Exception:
            pass
        for node_id in node_candidates:
            node_text = str(node_id)
            if not traffic_light_junctions or node_text in traffic_light_junctions:
                junctions.add(node_text)
    return junctions


def _connection_has_pedestrian_signal_lane(conn) -> bool:
    return any(_lane_is_pedestrian_signal_lane(lane) for lane in _connection_lanes(conn))


def _lane_is_pedestrian_signal_lane(lane) -> bool:
    lane_id = ""
    edge_id = ""
    try:
        lane_id = str(lane.getID())
    except Exception:
        lane_id = ""
    try:
        edge_id = str(lane.getEdge().getID())
    except Exception:
        edge_id = ""
    lowered = f"{lane_id} {edge_id}".lower()
    if "crossing" in lowered or "walkingarea" in lowered:
        return True
    try:
        pedestrian = bool(lane.allows("pedestrian"))
    except Exception:
        pedestrian = False
    if not pedestrian:
        return False
    for vehicle_class in ("passenger", "private", "bus", "truck", "taxi", "delivery"):
        try:
            if lane.allows(vehicle_class):
                return False
        except Exception:
            continue
    return True


def _lane_edge_id(lane) -> str:
    try:
        edge = lane.getEdge()
        return str(edge.getID())
    except Exception:
        return ""


def _tls_sensitive_pedestrian_pairs(
    net: Path,
    pedestrian_edges: Sequence[str],
    edge_nodes: dict,
) -> tuple[list[tuple[str, str]], list[str], str]:
    tls_junctions = _tls_junction_ids(net)
    if not tls_junctions:
        return [], [], "Could not generate TLS-sensitive pedestrian routes: no traffic_light junctions found."

    by_junction: dict[str, list[str]] = {junction: [] for junction in tls_junctions}
    for edge_id in pedestrian_edges:
        from_node, to_node = edge_nodes.get(edge_id, ("", ""))
        for node_id in (from_node, to_node):
            if node_id in by_junction:
                by_junction[node_id].append(edge_id)

    pairs: list[tuple[str, str]] = []
    sensitive_edges: set[str] = set()
    for junction_id in sorted(by_junction):
        node_edges = sorted(dict.fromkeys(by_junction[junction_id]))
        if len(node_edges) < 2:
            continue
        half = max(1, len(node_edges) // 2)
        for idx, from_edge in enumerate(node_edges):
            to_edge = node_edges[(idx + half) % len(node_edges)]
            if to_edge == from_edge:
                continue
            pairs.append((from_edge, to_edge))
            sensitive_edges.add(from_edge)
            sensitive_edges.add(to_edge)
    if not pairs:
        return [], [], "Could not generate TLS-sensitive pedestrian routes; pedestrian metrics may be identical."
    return pairs, sorted(sensitive_edges), ""


def _tls_junction_ids(net: Path) -> set[str]:
    try:
        root = ET.parse(net).getroot()
    except Exception:
        return set()
    result = set()
    for junction in root.findall("junction"):
        junction_type = str(junction.get("type", "")).lower()
        if "traffic_light" in junction_type:
            junction_id = junction.get("id")
            if junction_id:
                result.add(str(junction_id))
    return result


def _write_pedestrian_metadata(path: Path, payload: dict) -> None:
    try:
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    except Exception:
        pass


def _load_autogenerated_pedestrian_metadata(scenario_dir: Path) -> dict:
    path = Path(scenario_dir) / AUTOGENERATED_PEDESTRIANS_META
    try:
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            return data if isinstance(data, dict) else {}
    except Exception:
        return {}
    return {}


def _smoke_test_pedestrian_file(scenario_dir: Path, net: Path, pedestrian_file: Path) -> Tuple[bool, str]:
    sumo_cmd = detect_sumo_cmd(use_gui=False)
    if not sumo_cmd:
        return False, "sumo executable not found"
    tmp_sumocfg = Path(scenario_dir) / "_pedestrian_smoke.sumocfg"
    tmp_scenario = ScenarioFiles(
        scenario_dir=Path(scenario_dir),
        sumocfg=tmp_sumocfg,
        net=Path(net),
        route_files=[Path(pedestrian_file)],
        found=True,
    )
    write_sumocfg(tmp_scenario, begin=0, end=30, step_length=1)
    try:
        result = subprocess.run(
            [
                sumo_cmd,
                "-c",
                str(tmp_sumocfg),
                "--no-step-log",
                "true",
                "--no-warnings",
                "true",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except subprocess.TimeoutExpired:
        return False, "SUMO pedestrian smoke-test timed out after 30 seconds"
    try:
        tmp_sumocfg.unlink(missing_ok=True)
    except Exception:
        pass
    if result.returncode == 0:
        return True, ""
    return False, result.stderr.strip() or result.stdout.strip() or "SUMO pedestrian smoke-test failed"


def write_sumocfg(
    scenario: ScenarioFiles,
    begin: float,
    end: float,
    step_length: float,
    output_path: Optional[Path] = None,
    additional_files: Optional[Sequence[Path]] = None,
    update_scenario: bool = True,
) -> Path:
    if not scenario.net or not scenario.route_files:
        raise ValueError("Нельзя создать sumocfg без net-file и route-files.")

    sumocfg = Path(output_path) if output_path is not None else scenario.sumocfg or (scenario.scenario_dir / AUTOGENERATED_SUMOCFG)
    net_value = _relative_value(scenario.net, scenario.scenario_dir)
    route_value = ",".join(_relative_value(path, scenario.scenario_dir) for path in scenario.route_files)
    effective_additional = list(additional_files) if additional_files is not None else list(scenario.additional_files)
    additional_value = ",".join(
        _relative_value(path, scenario.scenario_dir) for path in effective_additional
    )

    additional_block = ""
    if additional_value:
        additional_block = f'        <additional-files value="{escape(additional_value)}"/>\n'

    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<configuration>\n"
        "    <input>\n"
        f'        <net-file value="{escape(net_value)}"/>\n'
        f'        <route-files value="{escape(route_value)}"/>\n'
        f"{additional_block}"
        "    </input>\n"
        "    <time>\n"
        f'        <begin value="{begin:g}"/>\n'
        f'        <end value="{end:g}"/>\n'
        f'        <step-length value="{step_length:g}"/>\n'
        "    </time>\n"
        "    <processing>\n"
        '        <time-to-teleport value="-1"/>\n'
        "    </processing>\n"
        "    <report>\n"
        '        <no-step-log value="true"/>\n'
        '        <duration-log.disable value="true"/>\n'
        "    </report>\n"
        "    <traci_server>\n"
        '        <quit-on-end value="true"/>\n'
        "    </traci_server>\n"
        "</configuration>\n"
    )
    sumocfg.write_text(xml, encoding="utf-8")
    if update_scenario:
        scenario.sumocfg = sumocfg
        scenario.autogenerated = sumocfg.name.lower() in {
            AUTOGENERATED_SUMOCFG,
            AUTOGENERATED_NATIVE_SUMOCFG,
            AUTOGENERATED_REAL_TIMING_SUMOCFG,
            AUTOGENERATED_RL_SUMOCFG,
        }
        scenario.found = True
    return sumocfg


def write_mode_sumocfgs(
    scenario: ScenarioFiles,
    begin: float,
    end: float,
    step_length: float,
    rl_use_real_timing_program_as_base: bool = True,
) -> dict:
    ordinary = list(scenario.additional_files)
    timing = [scenario.real_timing_file] if scenario.real_timing_file else []
    native = scenario.scenario_dir / AUTOGENERATED_NATIVE_SUMOCFG
    real_timing = scenario.scenario_dir / AUTOGENERATED_REAL_TIMING_SUMOCFG
    rl = scenario.scenario_dir / AUTOGENERATED_RL_SUMOCFG
    legacy = scenario.scenario_dir / AUTOGENERATED_SUMOCFG

    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=native,
        additional_files=ordinary,
        update_scenario=False,
    )
    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=legacy,
        additional_files=ordinary,
        update_scenario=False,
    )
    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=real_timing,
        additional_files=[*ordinary, *timing],
        update_scenario=False,
    )
    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=rl,
        additional_files=[*ordinary, *timing] if rl_use_real_timing_program_as_base else ordinary,
        update_scenario=False,
    )

    scenario.mode_sumocfgs = {
        "fixed_native": native,
        "fixed": native,
        "native": native,
        "real_timing": real_timing,
        "rl": rl,
    }
    scenario.sumocfg = native
    scenario.autogenerated = True
    scenario.found = True
    return dict(scenario.mode_sumocfgs)


def build_sumo_command(
    scenario: ScenarioFiles,
    use_gui: bool,
    seed: int,
    step_length: float,
    extra_args: Optional[Sequence[str]] = None,
    end: Optional[float] = None,
    mode: str = "fixed_native",
) -> List[str]:
    sumocfg = scenario.sumocfg_for_mode(mode)
    if not sumocfg:
        raise RuntimeError("Для запуска SUMO нужен .sumocfg. Сценарий не был подготовлен.")

    sumo_cmd = detect_sumo_cmd(use_gui=use_gui)
    if not sumo_cmd:
        raise RuntimeError("Не найдена команда sumo. Проверьте SUMO_HOME/bin и PATH.")

    cmd = [
        sumo_cmd,
        "-c",
        str(sumocfg),
        "--seed",
        str(int(seed)),
        "--step-length",
        str(float(step_length)),
    ]
    if extra_args:
        cmd.extend(str(arg) for arg in extra_args)
    if end is not None:
        cmd.extend(["--end", str(float(end))])
    return cmd


def validate_scenario_start(
    scenario: ScenarioFiles,
    use_gui: bool,
    seed: int,
    step_length: float,
    extra_args: Optional[Sequence[str]] = None,
    steps: int = 10,
) -> Tuple[bool, str, List[str]]:
    add_sumo_tools_to_path()
    try:
        import traci
    except Exception as exc:
        return False, f"Python не может импортировать traci: {exc}", []

    label = f"scenario_check_{uuid.uuid4().hex[:8]}"
    conn = None
    try:
        cmd = build_sumo_command(
            scenario,
            use_gui=use_gui,
            seed=seed,
            step_length=step_length,
            extra_args=extra_args,
            end=max(float(step_length), float(steps) * float(step_length)),
        )
        if not use_gui:
            cmd.extend(["--no-warnings", "true"])
        try:
            traci.start(cmd, label=label, numRetries=30)
        except TypeError:
            traci.start(cmd, label=label)
        conn = traci.getConnection(label)
        tls_ids = list(conn.trafficlight.getIDList())
        for _ in range(max(1, int(steps))):
            conn.simulationStep()
        return True, "", tls_ids
    except Exception as exc:
        return False, f"SUMO/TraCI не смог запустить сценарий: {exc}", []
    finally:
        if conn is not None:
            try:
                conn.close(False)
            except Exception:
                pass


def validate_scenario_subprocess(
    scenario: ScenarioFiles,
    seed: int,
    step_length: float,
    extra_args: Optional[Sequence[str]] = None,
    seconds: int = 10,
) -> Tuple[bool, str]:
    try:
        cmd = build_sumo_command(
            scenario,
            use_gui=False,
            seed=seed,
            step_length=step_length,
            extra_args=extra_args,
            end=seconds,
        )
    except Exception as exc:
        return False, str(exc)
    cmd.extend(["--no-warnings", "true"])
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=max(30, int(seconds) + 10))
    except subprocess.TimeoutExpired:
        return False, f"SUMO validation timed out after {max(30, int(seconds) + 10)} seconds"
    if result.returncode == 0:
        return True, ""
    message = result.stderr.strip() or result.stdout.strip() or "нет вывода SUMO"
    return False, message


def describe_scenario(scenario: ScenarioFiles, tls_ids: Optional[Sequence[str]] = None) -> List[str]:
    lines = [
        f"sumocfg: {_display_path(scenario.sumocfg)}",
        f"net-file: {_display_path(scenario.net)}",
        "route-files: "
        + (", ".join(_display_path(path) for path in scenario.route_files) if scenario.route_files else "-"),
        "additional-files: "
        + (
            ", ".join(_display_path(path) for path in scenario.additional_files)
            if scenario.additional_files
            else "-"
        ),
        "timing-files: "
        + (
            ", ".join(_display_path(path) for path in scenario.timing_files)
            if scenario.timing_files
            else "-"
        ),
    ]
    if scenario.mode_sumocfgs:
        for mode, path in sorted(scenario.mode_sumocfgs.items()):
            if mode in {"fixed", "native"}:
                continue
            lines.append(f"{mode}-sumocfg: {_display_path(path)}")
    if tls_ids is not None:
        lines.append(f"TLS found: {len(tls_ids)}")
        lines.append("TLS ids: " + (", ".join(tls_ids) if tls_ids else "-"))
    if scenario.notes:
        lines.extend(f"note: {note}" for note in scenario.notes)
    return lines


def _scenario_from_sumocfg(scenario_dir: Path, sumocfg: Path, source: str) -> ScenarioFiles:
    scenario = ScenarioFiles(
        scenario_dir=scenario_dir,
        sumocfg=sumocfg,
        autogenerated=sumocfg.name.lower() == AUTOGENERATED_SUMOCFG,
        found=True,
        source=source,
    )
    try:
        tree = ET.parse(sumocfg)
        root = tree.getroot()
    except Exception as exc:
        scenario.notes.append(f"Не удалось разобрать sumocfg: {exc}")
        return scenario

    base_dir = sumocfg.parent
    net_values = _config_values(root, {"net-file"})
    route_values = _config_values(root, {"route-file", "route-files"})
    additional_values = _config_values(root, {"additional-file", "additional-files"})

    if net_values:
        scenario.net = _resolve_config_path(base_dir, net_values[0])
    scenario.route_files = [_resolve_config_path(base_dir, value) for value in route_values]
    scenario.additional_files = [_resolve_config_path(base_dir, value) for value in additional_values]
    scenario.additional_files, scenario.timing_files = _split_timing_files(scenario.additional_files)
    return scenario


def _select_net_file(
    scenario_dir: Path,
    explicit: Optional[Path],
    preferred_prefix: str = "kaliningrad",
) -> Optional[Path]:
    explicit_path = _resolve_optional_path(scenario_dir, explicit)
    if explicit_path and explicit_path.exists():
        return explicit_path

    if preferred_prefix:
        preferred = scenario_dir / f"{preferred_prefix}.net.xml"
        if preferred.exists():
            return preferred

    matches = sorted(scenario_dir.glob("*.net.xml"))
    if matches:
        return matches[0]

    fallback = scenario_dir / "net.xml"
    return fallback if fallback.exists() else None


def _select_route_files(
    scenario_dir: Path,
    explicit: Optional[Path],
    selected_net: Optional[Path] = None,
    preferred_prefix: str = "kaliningrad",
    allow_mixed_scenario_files: bool = False,
) -> List[Path]:
    explicit_path = _resolve_optional_path(scenario_dir, explicit)
    if explicit_path and explicit_path.exists():
        prefix = _route_prefix(explicit_path)
        vtypes = scenario_dir / f"{prefix}.vtypes.xml" if prefix else None
        if vtypes and vtypes.exists() and vtypes.resolve() != explicit_path.resolve():
            return [vtypes, explicit_path]
        preferred_vtypes = scenario_dir / f"{preferred_prefix}.vtypes.xml" if preferred_prefix else None
        if (
            preferred_vtypes
            and preferred_vtypes.exists()
            and preferred_vtypes.resolve() != explicit_path.resolve()
        ):
            return [preferred_vtypes, explicit_path]
        return [explicit_path]

    net_prefix = _net_prefix(selected_net) if selected_net else ""
    prefix_routes = _route_files_for_prefix(scenario_dir, net_prefix)
    if prefix_routes:
        return prefix_routes

    if (
        selected_net
        and net_prefix
        and preferred_prefix
        and net_prefix.lower() == str(preferred_prefix).lower()
        and not bool(allow_mixed_scenario_files)
    ):
        candidates = [
            path
            for path in sorted(
                list(scenario_dir.glob("*.rou.xml"))
                + list(scenario_dir.glob("*.routes.xml"))
                + list(scenario_dir.glob("*.trips.xml"))
            )
            if path.name != AUTOGENERATED_PEDESTRIANS
            and path.name != AUTOGENERATED_DIAGNOSTIC_DEMAND
        ]
        if candidates:
            raise ValueError(
                "Scenario file mismatch: selected "
                f"{Path(selected_net).name} but route file {candidates[0].name} "
                "seems to belong to another scenario."
            )
        return []

    matches = sorted(
        list(scenario_dir.glob("*.rou.xml"))
        + list(scenario_dir.glob("*.routes.xml"))
        + list(scenario_dir.glob("*.trips.xml"))
    )
    matches = [
        path
        for path in matches
        if path.name not in {AUTOGENERATED_PEDESTRIANS, AUTOGENERATED_DIAGNOSTIC_DEMAND}
    ]
    if matches:
        return _unique_paths(matches)

    fallback = scenario_dir / "rou.xml"
    if fallback.exists():
        return [fallback]

    detected = []
    for path in sorted(scenario_dir.glob("*.xml")):
        lower_name = path.name.lower()
        if lower_name.endswith((".net.xml", ".add.xml", ".poly.xml")):
            continue
        kind, _ = _classify_xml(path)
        if kind == "route":
            detected.append(path)
    return _unique_paths(detected)


def _classify_companion_xml(
    scenario_dir: Path,
    net: Path,
    route_files: Sequence[Path],
    scenario_prefix: str = "",
    allow_mixed_scenario_files: bool = True,
    include_companion_routes: bool = True,
) -> Tuple[List[Path], List[Path], List[Path], List[str]]:
    selected_routes = _unique_paths(route_files)
    route_set = {path.resolve() for path in selected_routes}
    excluded = {net.resolve(), *route_set}
    notes: List[str] = []
    additional_files: List[Path] = []
    timing_files: List[Path] = []

    for path in sorted(scenario_dir.glob("*.xml")):
        resolved = path.resolve()
        if resolved in excluded:
            continue
        if path.name.lower().endswith(".sumocfg"):
            continue
        if path.name.lower() in {
            AUTOGENERATED_SUMOCFG,
            AUTOGENERATED_NATIVE_SUMOCFG,
            AUTOGENERATED_REAL_TIMING_SUMOCFG,
            AUTOGENERATED_RL_SUMOCFG,
            AUTOGENERATED_FILTERED_TIMING,
        }:
            continue
        if path.name in {AUTOGENERATED_PEDESTRIANS, AUTOGENERATED_DIAGNOSTIC_DEMAND}:
            continue
        if path.name.lower().endswith(".net.xml"):
            continue
        if path.suffix.lower() != ".xml":
            continue

        kind, tags = _classify_xml(path)
        if kind == "route":
            if not include_companion_routes:
                continue
            if (
                scenario_prefix
                and not bool(allow_mixed_scenario_files)
                and not _route_file_belongs_to_prefix(path, scenario_prefix)
            ):
                notes.append(
                    "Scenario file mismatch avoided: selected "
                    f"{Path(net).name} but route file {path.name} seems to belong to another scenario."
                )
                continue
            if path.name.lower() == "rou.xml" and any(
                route.name.lower() != "rou.xml" for route in selected_routes
            ):
                notes.append(f"{path.name} пропущен: основной маршрут уже выбран по шаблону *.rou.xml.")
                continue
            selected_routes.append(path)
            route_set.add(resolved)
            continue
        if kind == "additional":
            additional_files.append(path)
            continue
        if kind == "timing":
            timing_files.append(path)
            continue
        if PERSON_TAGS.intersection(tags):
            selected_routes.append(path)
            route_set.add(resolved)
            continue
        if path.name.lower().endswith((".add.xml", ".poly.xml")):
            additional_files.append(path)

    selected_routes, duplicate_notes = _drop_conflicting_route_files(selected_routes)
    notes.extend(duplicate_notes)
    additional_files, timing_from_additional = _split_timing_files(additional_files)
    timing_files.extend(timing_from_additional)
    return _unique_paths(selected_routes), _unique_paths(additional_files), _unique_paths(timing_files), notes


def _classify_xml(path: Path) -> Tuple[str, Set[str]]:
    tags: Set[str] = set()
    root_name = ""
    try:
        for _, elem in ET.iterparse(path, events=("start",)):
            name = _local_name(elem.tag)
            if not root_name:
                root_name = name
            tags.add(name)
            if len(tags) > 64 and (tags.intersection(ROUTE_TAGS) or tags.intersection(ADDITIONAL_TAGS)):
                break
    except Exception:
        return "unknown", tags

    lower_name = path.name.lower()
    if TIMING_TAGS.intersection(tags):
        return "timing", tags
    if root_name == "routes" or PERSON_TAGS.intersection(tags):
        return "route", tags
    if {"vehicle", "trip", "flow"}.intersection(tags):
        return "route", tags
    if root_name == "additional" or tags.intersection(ADDITIONAL_TAGS) or lower_name.endswith((".add.xml", ".poly.xml")):
        return "additional", tags
    if tags.intersection(ROUTE_TAGS):
        return "route", tags
    return "unknown", tags


def _drop_conflicting_route_files(route_files: Sequence[Path]) -> Tuple[List[Path], List[str]]:
    selected: List[Path] = []
    seen_ids: Set[str] = set()
    notes: List[str] = []

    for path in route_files:
        ids = _route_object_ids(path)
        duplicates = seen_ids.intersection(ids)
        if duplicates:
            preview = ", ".join(sorted(list(duplicates))[:5])
            notes.append(
                f"{path.name} skipped: duplicate route object ids already exist in earlier route files ({preview})."
            )
            continue
        selected.append(path)
        seen_ids.update(ids)
    return selected, notes


def _route_object_ids(path: Path) -> Set[str]:
    ids: Set[str] = set()
    id_tags = {
        "route",
        "vehicle",
        "trip",
        "flow",
        "person",
        "personFlow",
        "vType",
        "vTypeDistribution",
        "routeDistribution",
    }
    try:
        for _, elem in ET.iterparse(path, events=("start",)):
            if _local_name(elem.tag) in id_tags:
                obj_id = elem.attrib.get("id")
                if obj_id:
                    ids.add(obj_id)
    except Exception:
        return set()
    return ids


def _split_timing_files(paths: Sequence[Path]) -> Tuple[List[Path], List[Path]]:
    ordinary: List[Path] = []
    timing: List[Path] = []
    for path in paths:
        kind, tags = _classify_xml(Path(path))
        if kind == "timing" or TIMING_TAGS.intersection(tags):
            timing.append(Path(path))
        else:
            ordinary.append(Path(path))
    return _unique_paths(ordinary), _unique_paths(timing)


def _select_real_timing_file(timing_files: Sequence[Path], preferred_name: str) -> Optional[Path]:
    if not timing_files:
        return None
    preferred = str(preferred_name).lower()
    for path in timing_files:
        if Path(path).name.lower() == preferred:
            return Path(path)
    return Path(timing_files[0])


def _config_values(root: ET.Element, tag_names: Set[str]) -> List[str]:
    values: List[str] = []
    for elem in root.iter():
        if _local_name(elem.tag) not in tag_names:
            continue
        value = elem.attrib.get("value", "")
        values.extend(_split_config_value(value))
    return values


def _split_config_value(value: str) -> List[str]:
    chunks = []
    for item in value.replace(";", ",").split(","):
        item = item.strip()
        if item:
            chunks.append(item)
    return chunks


def _resolve_config_path(base_dir: Path, value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (base_dir / path).resolve()


def _resolve_optional_path(base_dir: Path, value: Optional[Path]) -> Optional[Path]:
    if value is None:
        return None
    path = Path(value)
    if path.is_absolute():
        return path
    return base_dir / path


def _relative_value(path: Path, base_dir: Path) -> str:
    try:
        rel = Path(path).resolve().relative_to(base_dir.resolve())
        return rel.as_posix()
    except Exception:
        return Path(path).as_posix()


def _unique_paths(paths: Iterable[Path]) -> List[Path]:
    result: List[Path] = []
    seen = set()
    for path in paths:
        resolved = Path(path).resolve()
        if resolved in seen:
            continue
        seen.add(resolved)
        result.append(Path(path))
    return result


def _local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def _display_path(path: Optional[Path]) -> str:
    return str(path) if path else "-"


def _net_prefix(path: Optional[Path]) -> str:
    if not path:
        return ""
    name = Path(path).name
    suffix = ".net.xml"
    if name.lower().endswith(suffix):
        return name[: -len(suffix)]
    return Path(path).stem


def _route_prefix(path: Optional[Path]) -> str:
    if not path:
        return ""
    name = Path(path).name
    for suffix in (".rou.xml", ".routes.xml", ".trips.xml", ".vtypes.xml"):
        if name.lower().endswith(suffix):
            return name[: -len(suffix)]
    return ""


def _route_files_for_prefix(scenario_dir: Path, prefix: str) -> List[Path]:
    if not prefix:
        return []
    ordered: List[Path] = []
    vtypes = scenario_dir / f"{prefix}.vtypes.xml"
    if vtypes.exists():
        ordered.append(vtypes)
    for suffix in (".rou.xml", ".routes.xml", ".trips.xml"):
        candidate = scenario_dir / f"{prefix}{suffix}"
        if candidate.exists():
            ordered.append(candidate)
    main_routes = [path for path in ordered if not path.name.lower().endswith(".vtypes.xml")]
    if not main_routes:
        return []
    return _unique_paths(ordered)


def _route_file_belongs_to_prefix(path: Path, prefix: str) -> bool:
    if not prefix:
        return True
    return Path(path).name.lower().startswith(str(prefix).lower() + ".")


def _select_osm_file(scenario_dir: Path, prefix: str) -> Optional[Path]:
    if prefix:
        preferred = scenario_dir / f"{prefix}.osm"
        if preferred.exists():
            return preferred
    matches = sorted(scenario_dir.glob("*.osm"))
    return matches[0] if matches else None


def _net_tls_ids(net: Optional[Path]) -> Set[str]:
    ids: Set[str] = set()
    if not net:
        return ids
    try:
        for _, elem in ET.iterparse(net, events=("start",)):
            name = _local_name(elem.tag)
            if name == "tlLogic":
                tls_id = elem.attrib.get("id")
                if tls_id:
                    ids.add(tls_id)
            elif name == "junction" and elem.attrib.get("type") == "traffic_light":
                tls_id = elem.attrib.get("id")
                if tls_id:
                    ids.add(tls_id)
    except Exception:
        return ids
    return ids


def _timing_tls_ids(path: Optional[Path]) -> Set[str]:
    ids: Set[str] = set()
    if not path:
        return ids
    try:
        for _, elem in ET.iterparse(path, events=("start",)):
            if _local_name(elem.tag) == "tlLogic":
                tls_id = elem.attrib.get("id")
                if tls_id:
                    ids.add(tls_id)
    except Exception:
        return ids
    return ids


def _prepare_real_timing_file(scenario: ScenarioFiles) -> Optional[Path]:
    timing_file = scenario.real_timing_file
    if not timing_file:
        return None
    net_ids = _net_tls_ids(scenario.net)
    timing_ids = _timing_tls_ids(timing_file)
    if not net_ids or not timing_ids:
        return timing_file

    matching = sorted(timing_ids.intersection(net_ids))
    missing = sorted(timing_ids.difference(net_ids))
    scenario.timing_matching_tls = matching
    scenario.timing_missing_tls = missing
    if missing:
        preview = ", ".join(missing[:10])
        scenario.notes.append(
            f"WARNING: {Path(timing_file).name} references TLS not found in {Path(scenario.net).name}: {preview}"
        )
    if not matching:
        scenario.notes.append(
            f"{Path(timing_file).name} skipped for real_timing baseline because no tlLogic id matches the selected net-file."
        )
        scenario.timing_files = [
            path for path in scenario.timing_files if Path(path).resolve() != Path(timing_file).resolve()
        ]
        return None
    if not missing:
        return timing_file

    filtered = scenario.scenario_dir / AUTOGENERATED_FILTERED_TIMING
    _write_filtered_timing_file(timing_file, filtered, set(matching))
    scenario.timing_filtered_file = filtered
    scenario.timing_files = _unique_paths(
        [path for path in scenario.timing_files if Path(path).resolve() != Path(timing_file).resolve()]
        + [filtered]
    )
    scenario.notes.append(
        f"Created {AUTOGENERATED_FILTERED_TIMING} with matching TLS only for real_timing baseline."
    )
    return filtered


def _write_filtered_timing_file(source: Path, output: Path, allowed_tls: Set[str]) -> None:
    tree = ET.parse(source)
    root = tree.getroot()
    filtered_root = ET.Element("additional")
    for child in list(root):
        if _local_name(child.tag) == "tlLogic" and child.attrib.get("id") in allowed_tls:
            filtered_root.append(copy.deepcopy(child))
    ET.ElementTree(filtered_root).write(output, encoding="utf-8", xml_declaration=True)


def _count_persons(path: Path) -> int:
    count = 0
    try:
        for _, elem in ET.iterparse(path, events=("start",)):
            if _local_name(elem.tag) in {"person", "personFlow"}:
                count += 1
    except Exception:
        return 0
    return count


def _estimate_route_counts(route_files: Sequence[Path]) -> dict:
    counts = {
        "vehicles": 0,
        "trips": 0,
        "flows": 0,
        "persons": 0,
        "person_flows": 0,
        "vtypes": 0,
    }
    for path in route_files:
        try:
            for _, elem in ET.iterparse(path, events=("start",)):
                name = _local_name(elem.tag)
                if name == "vehicle":
                    counts["vehicles"] += 1
                elif name == "trip":
                    counts["trips"] += 1
                elif name == "flow":
                    counts["flows"] += 1
                elif name == "person":
                    counts["persons"] += 1
                elif name == "personFlow":
                    counts["person_flows"] += 1
                elif name in {"vType", "vTypeDistribution"}:
                    counts["vtypes"] += 1
        except Exception:
            continue
    counts["vehicle_count_estimate"] = counts["vehicles"] + counts["trips"] + counts["flows"]
    counts["pedestrian_count_estimate"] = counts["persons"] + counts["person_flows"]
    return counts


def _estimate_net_lane_counts(net: Optional[Path]) -> dict:
    counts = {
        "vehicle_lanes_count": 0,
        "pedestrian_lanes_count": 0,
        "internal_lanes_count": 0,
    }
    if not net:
        return counts
    try:
        for _, elem in ET.iterparse(net, events=("start",)):
            if _local_name(elem.tag) != "lane":
                continue
            lane_id = elem.attrib.get("id", "")
            if lane_id.startswith(":"):
                counts["internal_lanes_count"] += 1
                continue
            allow = set((elem.attrib.get("allow") or "").split())
            disallow = set((elem.attrib.get("disallow") or "").split())
            is_walk = "walkingarea" in lane_id.lower() or "crossing" in lane_id.lower()
            if is_walk or (allow and allow.issubset({"pedestrian"})):
                counts["pedestrian_lanes_count"] += 1
                continue
            if allow and not allow.intersection(VEHICLE_CLASSES):
                continue
            if "all" in disallow and not allow:
                continue
            counts["vehicle_lanes_count"] += 1
    except Exception:
        return counts
    return counts


def build_scenario_summary(scenario: ScenarioFiles, tls_ids: Optional[Sequence[str]] = None) -> dict:
    route_counts = _estimate_route_counts(scenario.route_files)
    lane_counts = _estimate_net_lane_counts(scenario.net)
    route_names = [Path(path).name for path in scenario.route_files]
    return {
        "net_file": Path(scenario.net).name if scenario.net else None,
        "route_files": route_names,
        "tls_count": len(tls_ids or []),
        "tls_ids": list(tls_ids or []),
        "vehicle_lanes_count": lane_counts["vehicle_lanes_count"],
        "pedestrian_lanes_count": lane_counts["pedestrian_lanes_count"],
        "route_vehicle_count_estimate": route_counts["vehicle_count_estimate"],
        "has_vtypes": bool(route_counts["vtypes"] or any(name.endswith(".vtypes.xml") for name in route_names)),
        "has_pedestrians": bool(
            route_counts["pedestrian_count_estimate"]
            or scenario.pedestrian_existing_found
            or scenario.pedestrian_autogenerated
            or scenario.pedestrian_route_file
        ),
        "generated_pedestrians": bool(scenario.pedestrian_autogenerated),
        "osm_file_present": bool(scenario.osm_file and Path(scenario.osm_file).exists()),
    }
