import subprocess
import uuid
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List, Optional, Sequence, Set, Tuple
from xml.sax.saxutils import escape

from .utils import add_sumo_tools_to_path, detect_sumo_cmd


AUTOGENERATED_SUMOCFG = "autogenerated.sumocfg"
AUTOGENERATED_NATIVE_SUMOCFG = "autogenerated_native.sumocfg"
AUTOGENERATED_REAL_TIMING_SUMOCFG = "autogenerated_real_timing.sumocfg"
AUTOGENERATED_RL_SUMOCFG = "autogenerated_rl.sumocfg"
AUTOGENERATED_PEDESTRIANS = "autogenerated_pedestrians.rou.xml"

ROUTE_TAGS = {
    "routes",
    "route",
    "routeDistribution",
    "routes",
    "vehicle",
    "trip",
    "flow",
    "person",
    "personFlow",
    "walk",
    "ride",
    "vType",
    "vTypeDistribution",
}

PERSON_TAGS = {"person", "personFlow", "walk"}
TIMING_TAGS = {"tlLogic"}

ADDITIONAL_TAGS = {
    "additional",
    "poly",
    "poi",
    "busStop",
    "trainStop",
    "containerStop",
    "parkingArea",
    "chargingStation",
    "inductionLoop",
    "laneAreaDetector",
    "instantInductionLoop",
    "multiEntryExitDetector",
    "entryExitDetector",
    "e1Detector",
    "e2Detector",
    "e3Detector",
    "calibrator",
    "rerouter",
    "routeProbe",
    "variableSpeedSign",
    "detector",
}


@dataclass
class ScenarioFiles:
    scenario_dir: Path
    sumocfg: Optional[Path] = None
    net: Optional[Path] = None
    route_files: List[Path] = field(default_factory=list)
    additional_files: List[Path] = field(default_factory=list)
    timing_files: List[Path] = field(default_factory=list)
    real_timing_file: Optional[Path] = None
    mode_sumocfgs: dict = field(default_factory=dict)
    autogenerated: bool = False
    found: bool = False
    source: str = "none"
    notes: List[str] = field(default_factory=list)
    pedestrian_existing_found: bool = False
    pedestrian_autogenerated: bool = False
    pedestrian_route_file: Optional[Path] = None
    pedestrian_count: int = 0

    @property
    def primary_route(self) -> Optional[Path]:
        return self.route_files[0] if self.route_files else None

    @property
    def primary_additional(self) -> Optional[Path]:
        return self.additional_files[0] if self.additional_files else None

    def as_legacy_dict(self) -> dict:
        return {
            "sumocfg": self.sumocfg,
            "net": self.net,
            "rou": self.primary_route,
            "add": self.primary_additional,
            "route_files": list(self.route_files),
            "additional_files": list(self.additional_files),
            "timing_files": list(self.timing_files),
            "real_timing_file": self.real_timing_file,
            "found": self.found,
        }

    def sumocfg_for_mode(self, mode: str) -> Optional[Path]:
        normalized = normalize_sumo_mode(mode)
        return self.mode_sumocfgs.get(normalized) or self.sumocfg


def normalize_sumo_mode(mode: str) -> str:
    if mode == "fixed":
        return "fixed_native"
    return str(mode or "fixed_native")


def discover_scenario(
    scenario_dir: Path,
    begin: float = 0.0,
    end: float = 300.0,
    step_length: float = 1.0,
    auto_generate_sumocfg: bool = True,
    scenario_sumocfg_file: Optional[Path] = None,
    scenario_net_file: Optional[Path] = None,
    scenario_route_file: Optional[Path] = None,
    auto_generate_pedestrians_if_missing: bool = False,
    pedestrian_count: int = 30,
    pedestrian_begin: int = 0,
    pedestrian_end: int = 300,
    pedestrian_prefix: str = "auto_ped",
    real_timing_file_name: str = "tls.add.xml",
    rl_use_real_timing_program_as_base: bool = True,
) -> ScenarioFiles:
    scenario_dir = Path(scenario_dir)
    scenario_dir.mkdir(parents=True, exist_ok=True)

    explicit_sumocfg = _resolve_optional_path(scenario_dir, scenario_sumocfg_file)
    if explicit_sumocfg and explicit_sumocfg.exists():
        scenario = _scenario_from_sumocfg(scenario_dir, explicit_sumocfg, source="explicit_sumocfg")
        return _finalize_scenario(
            scenario,
            begin,
            end,
            step_length,
            auto_generate_sumocfg,
            auto_generate_pedestrians_if_missing,
            pedestrian_count,
            pedestrian_begin,
            pedestrian_end,
            pedestrian_prefix,
            real_timing_file_name,
            rl_use_real_timing_program_as_base,
        )

    user_sumocfgs = [
        path
        for path in sorted(scenario_dir.glob("*.sumocfg"))
        if path.name.lower()
        not in {
            AUTOGENERATED_SUMOCFG,
            AUTOGENERATED_NATIVE_SUMOCFG,
            AUTOGENERATED_REAL_TIMING_SUMOCFG,
            AUTOGENERATED_RL_SUMOCFG,
        }
    ]
    if user_sumocfgs:
        scenario = _scenario_from_sumocfg(scenario_dir, user_sumocfgs[0], source="sumocfg")
        return _finalize_scenario(
            scenario,
            begin,
            end,
            step_length,
            auto_generate_sumocfg,
            auto_generate_pedestrians_if_missing,
            pedestrian_count,
            pedestrian_begin,
            pedestrian_end,
            pedestrian_prefix,
            real_timing_file_name,
            rl_use_real_timing_program_as_base,
        )

    net = _select_net_file(scenario_dir, scenario_net_file)
    route_files = [
        path
        for path in _select_route_files(scenario_dir, scenario_route_file)
        if path.name != AUTOGENERATED_PEDESTRIANS
    ]
    if not net or not route_files:
        generated = scenario_dir / AUTOGENERATED_SUMOCFG
        if generated.exists():
            parsed = _scenario_from_sumocfg(scenario_dir, generated, source="autogenerated_sumocfg")
            if parsed.net and parsed.route_files:
                return _finalize_scenario(
                    parsed,
                    begin,
                    end,
                    step_length,
                    auto_generate_sumocfg,
                    auto_generate_pedestrians_if_missing,
                    pedestrian_count,
                    pedestrian_begin,
                    pedestrian_end,
                    pedestrian_prefix,
                    real_timing_file_name,
                    rl_use_real_timing_program_as_base,
                )
        return ScenarioFiles(scenario_dir=scenario_dir, found=False)

    route_files, additional_files, timing_files, notes = _classify_companion_xml(scenario_dir, net, route_files)
    scenario = ScenarioFiles(
        scenario_dir=scenario_dir,
        net=net,
        route_files=route_files,
        additional_files=additional_files,
        timing_files=timing_files,
        found=True,
        source="net_and_routes",
        notes=notes,
    )
    return _finalize_scenario(
        scenario,
        begin,
        end,
        step_length,
        auto_generate_sumocfg,
        auto_generate_pedestrians_if_missing,
        pedestrian_count,
        pedestrian_begin,
        pedestrian_end,
        pedestrian_prefix,
        real_timing_file_name,
        rl_use_real_timing_program_as_base,
    )


def _finalize_scenario(
    scenario: ScenarioFiles,
    begin: float,
    end: float,
    step_length: float,
    auto_generate_sumocfg: bool,
    auto_generate_pedestrians_if_missing: bool,
    pedestrian_count: int,
    pedestrian_begin: int,
    pedestrian_end: int,
    pedestrian_prefix: str,
    real_timing_file_name: str,
    rl_use_real_timing_program_as_base: bool,
) -> ScenarioFiles:
    if not scenario.found:
        return scenario

    ordinary, timing = _split_timing_files(scenario.additional_files)
    scenario.additional_files = ordinary
    scenario.timing_files = _unique_paths([*scenario.timing_files, *timing])
    named_timing = scenario.scenario_dir / str(real_timing_file_name)
    if named_timing.exists() and named_timing not in scenario.timing_files:
        kind, _ = _classify_xml(named_timing)
        if kind == "timing":
            scenario.timing_files.append(named_timing)
    scenario.timing_files = _unique_paths(scenario.timing_files)
    scenario.real_timing_file = _select_real_timing_file(scenario.timing_files, real_timing_file_name)

    scenario.pedestrian_existing_found = route_files_have_pedestrians(scenario.route_files)
    if (
        scenario.net
        and not scenario.pedestrian_existing_found
        and auto_generate_pedestrians_if_missing
    ):
        ok, message, generated = generate_pedestrian_demand(
            scenario_dir=scenario.scenario_dir,
            net=scenario.net,
            count=pedestrian_count,
            begin=pedestrian_begin,
            end=pedestrian_end,
            prefix=pedestrian_prefix,
        )
        if ok and generated:
            scenario.route_files.append(generated)
            scenario.pedestrian_autogenerated = True
            scenario.pedestrian_route_file = generated
            scenario.pedestrian_count = int(pedestrian_count)
            scenario.notes.append("Пешеходы не найдены. Создан autogenerated_pedestrians.rou.xml для dev-проверки.")
        else:
            scenario.notes.append(message)
    if auto_generate_sumocfg:
        scenario.autogenerated = True
        write_mode_sumocfgs(
            scenario,
            begin=begin,
            end=end,
            step_length=step_length,
            rl_use_real_timing_program_as_base=rl_use_real_timing_program_as_base,
        )
    return scenario


def route_files_have_pedestrians(route_files: Sequence[Path]) -> bool:
    for path in route_files:
        try:
            _, tags = _classify_xml(Path(path))
            if PERSON_TAGS.intersection(tags):
                return True
        except Exception:
            continue
    return False


def generate_pedestrian_demand(
    scenario_dir: Path,
    net: Path,
    count: int,
    begin: int,
    end: int,
    prefix: str,
) -> Tuple[bool, str, Optional[Path]]:
    scenario_dir = Path(scenario_dir)
    output = scenario_dir / AUTOGENERATED_PEDESTRIANS
    try:
        add_sumo_tools_to_path()
        import sumolib

        sumo_net = sumolib.net.readNet(str(net), withInternal=True)
        edges = []
        for edge in sumo_net.getEdges():
            edge_id = edge.getID()
            if edge_id.startswith(":"):
                continue
            try:
                if edge.allows("pedestrian"):
                    edges.append(edge_id)
                    continue
            except Exception:
                pass
            try:
                if any(lane.allows("pedestrian") for lane in edge.getLanes()):
                    edges.append(edge_id)
            except Exception:
                continue
    except Exception as exc:
        return False, f"Could not generate pedestrian routes: {exc}", None

    if not edges:
        return False, "Could not generate pedestrian routes: no pedestrian-compatible edges found.", None

    edges = sorted(dict.fromkeys(edges))
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<routes>"]
    demand_count = max(1, int(count))
    begin = int(begin)
    end = max(begin + 1, int(end))
    for idx in range(demand_count):
        depart = begin + int((end - begin) * idx / max(1, demand_count))
        from_edge = edges[idx % len(edges)]
        to_edge = edges[(idx + max(1, len(edges) // 2)) % len(edges)]
        if to_edge == from_edge:
            to_edge = from_edge
        lines.append(f'    <person id="{prefix}_{idx}" depart="{depart}">')
        lines.append(f'        <walk from="{from_edge}" to="{to_edge}"/>')
        lines.append("    </person>")
    lines.append("</routes>")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")

    ok, message = _smoke_test_pedestrian_file(scenario_dir, net, output)
    if ok:
        return True, "", output

    # Fallback: same-edge walks are accepted by SUMO on networks where cross-edge
    # pedestrian routing is not available.
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<routes>"]
    for idx in range(demand_count):
        depart = begin + int((end - begin) * idx / max(1, demand_count))
        edge = edges[idx % len(edges)]
        lines.append(f'    <person id="{prefix}_{idx}" depart="{depart}">')
        lines.append(f'        <walk from="{edge}" to="{edge}"/>')
        lines.append("    </person>")
    lines.append("</routes>")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    ok, fallback_message = _smoke_test_pedestrian_file(scenario_dir, net, output)
    if ok:
        return True, "", output
    return False, f"Could not generate pedestrian routes: {message}; fallback failed: {fallback_message}", None


def _smoke_test_pedestrian_file(scenario_dir: Path, net: Path, pedestrian_file: Path) -> Tuple[bool, str]:
    sumo_cmd = detect_sumo_cmd(use_gui=False)
    if not sumo_cmd:
        return False, "sumo executable not found"
    tmp_sumocfg = Path(scenario_dir) / "_pedestrian_smoke.sumocfg"
    tmp_scenario = ScenarioFiles(
        scenario_dir=Path(scenario_dir),
        sumocfg=tmp_sumocfg,
        net=Path(net),
        route_files=[Path(pedestrian_file)],
        found=True,
    )
    write_sumocfg(tmp_scenario, begin=0, end=30, step_length=1)
    result = subprocess.run(
        [
            sumo_cmd,
            "-c",
            str(tmp_sumocfg),
            "--no-step-log",
            "true",
            "--no-warnings",
            "true",
        ],
        capture_output=True,
        text=True,
    )
    try:
        tmp_sumocfg.unlink(missing_ok=True)
    except Exception:
        pass
    if result.returncode == 0:
        return True, ""
    return False, result.stderr.strip() or result.stdout.strip() or "SUMO pedestrian smoke-test failed"


def write_sumocfg(
    scenario: ScenarioFiles,
    begin: float,
    end: float,
    step_length: float,
    output_path: Optional[Path] = None,
    additional_files: Optional[Sequence[Path]] = None,
    update_scenario: bool = True,
) -> Path:
    if not scenario.net or not scenario.route_files:
        raise ValueError("Нельзя создать sumocfg без net-file и route-files.")

    sumocfg = Path(output_path) if output_path is not None else scenario.sumocfg or (scenario.scenario_dir / AUTOGENERATED_SUMOCFG)
    net_value = _relative_value(scenario.net, scenario.scenario_dir)
    route_value = ",".join(_relative_value(path, scenario.scenario_dir) for path in scenario.route_files)
    effective_additional = list(additional_files) if additional_files is not None else list(scenario.additional_files)
    additional_value = ",".join(
        _relative_value(path, scenario.scenario_dir) for path in effective_additional
    )

    additional_block = ""
    if additional_value:
        additional_block = f'        <additional-files value="{escape(additional_value)}"/>\n'

    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<configuration>\n"
        "    <input>\n"
        f'        <net-file value="{escape(net_value)}"/>\n'
        f'        <route-files value="{escape(route_value)}"/>\n'
        f"{additional_block}"
        "    </input>\n"
        "    <time>\n"
        f'        <begin value="{begin:g}"/>\n'
        f'        <end value="{end:g}"/>\n'
        f'        <step-length value="{step_length:g}"/>\n'
        "    </time>\n"
        "    <processing>\n"
        '        <time-to-teleport value="-1"/>\n'
        "    </processing>\n"
        "    <report>\n"
        '        <no-step-log value="true"/>\n'
        '        <duration-log.disable value="true"/>\n'
        "    </report>\n"
        "    <traci_server>\n"
        '        <quit-on-end value="true"/>\n'
        "    </traci_server>\n"
        "</configuration>\n"
    )
    sumocfg.write_text(xml, encoding="utf-8")
    if update_scenario:
        scenario.sumocfg = sumocfg
        scenario.autogenerated = sumocfg.name.lower() in {
            AUTOGENERATED_SUMOCFG,
            AUTOGENERATED_NATIVE_SUMOCFG,
            AUTOGENERATED_REAL_TIMING_SUMOCFG,
            AUTOGENERATED_RL_SUMOCFG,
        }
        scenario.found = True
    return sumocfg


def write_mode_sumocfgs(
    scenario: ScenarioFiles,
    begin: float,
    end: float,
    step_length: float,
    rl_use_real_timing_program_as_base: bool = True,
) -> dict:
    ordinary = list(scenario.additional_files)
    timing = [scenario.real_timing_file] if scenario.real_timing_file else []
    native = scenario.scenario_dir / AUTOGENERATED_NATIVE_SUMOCFG
    real_timing = scenario.scenario_dir / AUTOGENERATED_REAL_TIMING_SUMOCFG
    rl = scenario.scenario_dir / AUTOGENERATED_RL_SUMOCFG
    legacy = scenario.scenario_dir / AUTOGENERATED_SUMOCFG

    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=native,
        additional_files=ordinary,
        update_scenario=False,
    )
    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=legacy,
        additional_files=ordinary,
        update_scenario=False,
    )
    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=real_timing,
        additional_files=[*ordinary, *timing],
        update_scenario=False,
    )
    write_sumocfg(
        scenario,
        begin,
        end,
        step_length,
        output_path=rl,
        additional_files=[*ordinary, *timing] if rl_use_real_timing_program_as_base else ordinary,
        update_scenario=False,
    )

    scenario.mode_sumocfgs = {
        "fixed_native": native,
        "fixed": native,
        "native": native,
        "real_timing": real_timing,
        "rl": rl,
    }
    scenario.sumocfg = native
    scenario.autogenerated = True
    scenario.found = True
    return dict(scenario.mode_sumocfgs)


def build_sumo_command(
    scenario: ScenarioFiles,
    use_gui: bool,
    seed: int,
    step_length: float,
    extra_args: Optional[Sequence[str]] = None,
    end: Optional[float] = None,
    mode: str = "fixed_native",
) -> List[str]:
    sumocfg = scenario.sumocfg_for_mode(mode)
    if not sumocfg:
        raise RuntimeError("Для запуска SUMO нужен .sumocfg. Сценарий не был подготовлен.")

    sumo_cmd = detect_sumo_cmd(use_gui=use_gui)
    if not sumo_cmd:
        raise RuntimeError("Не найдена команда sumo. Проверьте SUMO_HOME/bin и PATH.")

    cmd = [
        sumo_cmd,
        "-c",
        str(sumocfg),
        "--seed",
        str(int(seed)),
        "--step-length",
        str(float(step_length)),
    ]
    if extra_args:
        cmd.extend(str(arg) for arg in extra_args)
    if end is not None:
        cmd.extend(["--end", str(float(end))])
    return cmd


def validate_scenario_start(
    scenario: ScenarioFiles,
    use_gui: bool,
    seed: int,
    step_length: float,
    extra_args: Optional[Sequence[str]] = None,
    steps: int = 10,
) -> Tuple[bool, str, List[str]]:
    add_sumo_tools_to_path()
    try:
        import traci
    except Exception as exc:
        return False, f"Python не может импортировать traci: {exc}", []

    label = f"scenario_check_{uuid.uuid4().hex[:8]}"
    conn = None
    try:
        cmd = build_sumo_command(
            scenario,
            use_gui=use_gui,
            seed=seed,
            step_length=step_length,
            extra_args=extra_args,
            end=max(float(step_length), float(steps) * float(step_length)),
        )
        if not use_gui:
            cmd.extend(["--no-warnings", "true"])
        traci.start(cmd, label=label)
        conn = traci.getConnection(label)
        tls_ids = list(conn.trafficlight.getIDList())
        for _ in range(max(1, int(steps))):
            conn.simulationStep()
        return True, "", tls_ids
    except Exception as exc:
        return False, f"SUMO/TraCI не смог запустить сценарий: {exc}", []
    finally:
        if conn is not None:
            try:
                conn.close(False)
            except Exception:
                pass


def validate_scenario_subprocess(
    scenario: ScenarioFiles,
    seed: int,
    step_length: float,
    extra_args: Optional[Sequence[str]] = None,
    seconds: int = 10,
) -> Tuple[bool, str]:
    try:
        cmd = build_sumo_command(
            scenario,
            use_gui=False,
            seed=seed,
            step_length=step_length,
            extra_args=extra_args,
            end=seconds,
        )
    except Exception as exc:
        return False, str(exc)
    cmd.extend(["--no-warnings", "true"])
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode == 0:
        return True, ""
    message = result.stderr.strip() or result.stdout.strip() or "нет вывода SUMO"
    return False, message


def describe_scenario(scenario: ScenarioFiles, tls_ids: Optional[Sequence[str]] = None) -> List[str]:
    lines = [
        f"sumocfg: {_display_path(scenario.sumocfg)}",
        f"net-file: {_display_path(scenario.net)}",
        "route-files: "
        + (", ".join(_display_path(path) for path in scenario.route_files) if scenario.route_files else "-"),
        "additional-files: "
        + (
            ", ".join(_display_path(path) for path in scenario.additional_files)
            if scenario.additional_files
            else "-"
        ),
        "timing-files: "
        + (
            ", ".join(_display_path(path) for path in scenario.timing_files)
            if scenario.timing_files
            else "-"
        ),
    ]
    if scenario.mode_sumocfgs:
        for mode, path in sorted(scenario.mode_sumocfgs.items()):
            if mode in {"fixed", "native"}:
                continue
            lines.append(f"{mode}-sumocfg: {_display_path(path)}")
    if tls_ids is not None:
        lines.append(f"TLS found: {len(tls_ids)}")
        lines.append("TLS ids: " + (", ".join(tls_ids) if tls_ids else "-"))
    if scenario.notes:
        lines.extend(f"note: {note}" for note in scenario.notes)
    return lines


def _scenario_from_sumocfg(scenario_dir: Path, sumocfg: Path, source: str) -> ScenarioFiles:
    scenario = ScenarioFiles(
        scenario_dir=scenario_dir,
        sumocfg=sumocfg,
        autogenerated=sumocfg.name.lower() == AUTOGENERATED_SUMOCFG,
        found=True,
        source=source,
    )
    try:
        tree = ET.parse(sumocfg)
        root = tree.getroot()
    except Exception as exc:
        scenario.notes.append(f"Не удалось разобрать sumocfg: {exc}")
        return scenario

    base_dir = sumocfg.parent
    net_values = _config_values(root, {"net-file"})
    route_values = _config_values(root, {"route-file", "route-files"})
    additional_values = _config_values(root, {"additional-file", "additional-files"})

    if net_values:
        scenario.net = _resolve_config_path(base_dir, net_values[0])
    scenario.route_files = [_resolve_config_path(base_dir, value) for value in route_values]
    scenario.additional_files = [_resolve_config_path(base_dir, value) for value in additional_values]
    scenario.additional_files, scenario.timing_files = _split_timing_files(scenario.additional_files)
    return scenario


def _select_net_file(scenario_dir: Path, explicit: Optional[Path]) -> Optional[Path]:
    explicit_path = _resolve_optional_path(scenario_dir, explicit)
    if explicit_path and explicit_path.exists():
        return explicit_path

    matches = sorted(scenario_dir.glob("*.net.xml"))
    if matches:
        return matches[0]

    fallback = scenario_dir / "net.xml"
    return fallback if fallback.exists() else None


def _select_route_files(scenario_dir: Path, explicit: Optional[Path]) -> List[Path]:
    explicit_path = _resolve_optional_path(scenario_dir, explicit)
    if explicit_path and explicit_path.exists():
        return [explicit_path]

    matches = sorted(
        list(scenario_dir.glob("*.rou.xml"))
        + list(scenario_dir.glob("*.routes.xml"))
        + list(scenario_dir.glob("*.trips.xml"))
    )
    if matches:
        return _unique_paths(matches)

    fallback = scenario_dir / "rou.xml"
    if fallback.exists():
        return [fallback]

    detected = []
    for path in sorted(scenario_dir.glob("*.xml")):
        lower_name = path.name.lower()
        if lower_name.endswith((".net.xml", ".add.xml", ".poly.xml")):
            continue
        kind, _ = _classify_xml(path)
        if kind == "route":
            detected.append(path)
    return _unique_paths(detected)


def _classify_companion_xml(
    scenario_dir: Path,
    net: Path,
    route_files: Sequence[Path],
) -> Tuple[List[Path], List[Path], List[Path], List[str]]:
    selected_routes = _unique_paths(route_files)
    route_set = {path.resolve() for path in selected_routes}
    excluded = {net.resolve(), *route_set}
    notes: List[str] = []
    additional_files: List[Path] = []
    timing_files: List[Path] = []

    for path in sorted(scenario_dir.glob("*.xml")):
        resolved = path.resolve()
        if resolved in excluded:
            continue
        if path.name.lower().endswith(".sumocfg"):
            continue
        if path.name.lower() in {
            AUTOGENERATED_SUMOCFG,
            AUTOGENERATED_NATIVE_SUMOCFG,
            AUTOGENERATED_REAL_TIMING_SUMOCFG,
            AUTOGENERATED_RL_SUMOCFG,
        }:
            continue
        if path.name == AUTOGENERATED_PEDESTRIANS:
            continue
        if path.name.lower().endswith(".net.xml"):
            continue
        if path.suffix.lower() != ".xml":
            continue

        kind, tags = _classify_xml(path)
        if kind == "route":
            if path.name.lower() == "rou.xml" and any(
                route.name.lower() != "rou.xml" for route in selected_routes
            ):
                notes.append(f"{path.name} пропущен: основной маршрут уже выбран по шаблону *.rou.xml.")
                continue
            selected_routes.append(path)
            route_set.add(resolved)
            continue
        if kind == "additional":
            additional_files.append(path)
            continue
        if kind == "timing":
            timing_files.append(path)
            continue
        if PERSON_TAGS.intersection(tags):
            selected_routes.append(path)
            route_set.add(resolved)
            continue
        if path.name.lower().endswith((".add.xml", ".poly.xml")):
            additional_files.append(path)

    selected_routes, duplicate_notes = _drop_conflicting_route_files(selected_routes)
    notes.extend(duplicate_notes)
    additional_files, timing_from_additional = _split_timing_files(additional_files)
    timing_files.extend(timing_from_additional)
    return _unique_paths(selected_routes), _unique_paths(additional_files), _unique_paths(timing_files), notes


def _classify_xml(path: Path) -> Tuple[str, Set[str]]:
    tags: Set[str] = set()
    root_name = ""
    try:
        for _, elem in ET.iterparse(path, events=("start",)):
            name = _local_name(elem.tag)
            if not root_name:
                root_name = name
            tags.add(name)
            if len(tags) > 64 and (tags.intersection(ROUTE_TAGS) or tags.intersection(ADDITIONAL_TAGS)):
                break
    except Exception:
        return "unknown", tags

    lower_name = path.name.lower()
    if TIMING_TAGS.intersection(tags):
        return "timing", tags
    if root_name == "routes" or PERSON_TAGS.intersection(tags):
        return "route", tags
    if {"vehicle", "trip", "flow"}.intersection(tags):
        return "route", tags
    if root_name == "additional" or tags.intersection(ADDITIONAL_TAGS) or lower_name.endswith((".add.xml", ".poly.xml")):
        return "additional", tags
    if tags.intersection(ROUTE_TAGS):
        return "route", tags
    return "unknown", tags


def _drop_conflicting_route_files(route_files: Sequence[Path]) -> Tuple[List[Path], List[str]]:
    selected: List[Path] = []
    seen_ids: Set[str] = set()
    notes: List[str] = []

    for path in route_files:
        ids = _route_object_ids(path)
        duplicates = seen_ids.intersection(ids)
        if duplicates:
            preview = ", ".join(sorted(list(duplicates))[:5])
            notes.append(
                f"{path.name} skipped: duplicate route object ids already exist in earlier route files ({preview})."
            )
            continue
        selected.append(path)
        seen_ids.update(ids)
    return selected, notes


def _route_object_ids(path: Path) -> Set[str]:
    ids: Set[str] = set()
    id_tags = {
        "route",
        "vehicle",
        "trip",
        "flow",
        "person",
        "personFlow",
        "vType",
        "vTypeDistribution",
        "routeDistribution",
    }
    try:
        for _, elem in ET.iterparse(path, events=("start",)):
            if _local_name(elem.tag) in id_tags:
                obj_id = elem.attrib.get("id")
                if obj_id:
                    ids.add(obj_id)
    except Exception:
        return set()
    return ids


def _split_timing_files(paths: Sequence[Path]) -> Tuple[List[Path], List[Path]]:
    ordinary: List[Path] = []
    timing: List[Path] = []
    for path in paths:
        kind, tags = _classify_xml(Path(path))
        if kind == "timing" or TIMING_TAGS.intersection(tags):
            timing.append(Path(path))
        else:
            ordinary.append(Path(path))
    return _unique_paths(ordinary), _unique_paths(timing)


def _select_real_timing_file(timing_files: Sequence[Path], preferred_name: str) -> Optional[Path]:
    if not timing_files:
        return None
    preferred = str(preferred_name).lower()
    for path in timing_files:
        if Path(path).name.lower() == preferred:
            return Path(path)
    return Path(timing_files[0])


def _config_values(root: ET.Element, tag_names: Set[str]) -> List[str]:
    values: List[str] = []
    for elem in root.iter():
        if _local_name(elem.tag) not in tag_names:
            continue
        value = elem.attrib.get("value", "")
        values.extend(_split_config_value(value))
    return values


def _split_config_value(value: str) -> List[str]:
    chunks = []
    for item in value.replace(";", ",").split(","):
        item = item.strip()
        if item:
            chunks.append(item)
    return chunks


def _resolve_config_path(base_dir: Path, value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return (base_dir / path).resolve()


def _resolve_optional_path(base_dir: Path, value: Optional[Path]) -> Optional[Path]:
    if value is None:
        return None
    path = Path(value)
    if path.is_absolute():
        return path
    return base_dir / path


def _relative_value(path: Path, base_dir: Path) -> str:
    try:
        rel = Path(path).resolve().relative_to(base_dir.resolve())
        return rel.as_posix()
    except Exception:
        return Path(path).as_posix()


def _unique_paths(paths: Iterable[Path]) -> List[Path]:
    result: List[Path] = []
    seen = set()
    for path in paths:
        resolved = Path(path).resolve()
        if resolved in seen:
            continue
        seen.add(resolved)
        result.append(Path(path))
    return result


def _local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def _display_path(path: Optional[Path]) -> str:
    return str(path) if path else "-"
