import json
import os
import time
import uuid
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from . import training_params as params
from .config import ACTION_SIZE
from .features import build_observation, encode_phase_onehot
from .graph_utils import aggregate_neighbors, build_tls_graph_from_net
from .scenario import (
    AUTOGENERATED_PEDESTRIANS_META,
    build_sumo_command,
    discover_scenario,
    normalize_sumo_mode,
)
from .timing_profiles import load_timing_profile
from .utils import add_sumo_tools_to_path


PEDESTRIAN_ONLY_CLASSES = {"pedestrian"}
VEHICLE_CLASSES = {
    "passenger",
    "private",
    "taxi",
    "bus",
    "coach",
    "delivery",
    "truck",
    "trailer",
    "motorcycle",
    "moped",
    "bicycle",
    "evehicle",
    "emergency",
    "authority",
    "army",
    "vip",
    "hov",
    "custom1",
    "custom2",
}

_GRAPH_CACHE: Dict[str, Dict[str, List[str]]] = {}
GRAPH_BUILDING_SECONDS_TOTAL = 0.0


def get_graph_building_seconds() -> float:
    return float(GRAPH_BUILDING_SECONDS_TOTAL)


def _safe_float(value, default: float = 0.0) -> float:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return float(default)
    if not np.isfinite(result):
        return float(default)
    return result


class SumoMultiAgentEnv:
    def __init__(
        self,
        scenario_dir,
        use_gui: bool = False,
        step_length: float = params.STEP_LENGTH,
        episode_seconds: int = params.EPISODE_SECONDS,
        min_green: int = params.MIN_GREEN,
        alpha: float = params.REWARD_ALPHA_QUEUE,
        beta: float = params.REWARD_BETA_NEIGHBOR,
        obs_cfg=None,
        seed: int = params.SEED,
        sumo_extra_args: Optional[List[str]] = None,
        mode: str = "rl",
    ):
        self.scenario_dir = Path(scenario_dir)
        self.use_gui = bool(use_gui)
        self.step_length = float(step_length)
        self.episode_seconds = int(episode_seconds)
        self.min_green = int(min_green)
        self.alpha = float(alpha)
        self.beta = float(beta)
        self.obs_cfg = obs_cfg
        self.seed = int(seed)
        self.sumo_extra_args = list(sumo_extra_args) if sumo_extra_args is not None else None
        self.mode = normalize_sumo_mode(mode)

        self.conn = None
        self.label = f"sumo_rl_{uuid.uuid4().hex[:8]}"
        self.traci = None
        self.scenario = None

        self.tls_ids: List[str] = []
        self.all_tls_ids: List[str] = []
        self.metric_tls_ids: List[str] = []
        self.smoke_total_tls_count: int = 0
        self.smoke_controlled_tls_count: int = 0
        self.neighbors: Dict[str, List[str]] = {}
        self.num_phases_per_tls: Dict[str, int] = {}
        self.incoming_lanes: Dict[str, List[str]] = {}
        self.outgoing_lanes: Dict[str, List[str]] = {}
        self.time_since_switch_by_tls: Dict[str, float] = {}
        self.last_phase_by_tls: Dict[str, int] = {}
        self.max_phases_global: int = 1
        self.obs_size: int = 0
        self.action_size: int = ACTION_SIZE

        self.sim_time: float = 0.0
        self.step_count: int = 0
        self.total_arrived: int = 0
        self.total_departed: int = 0
        self.pedestrian_departed_total: int = 0
        self.pedestrian_arrived_total: int = 0
        self.pedestrian_running_max: int = 0
        self.pedestrian_waiting_count_sum: int = 0
        self.pedestrian_waiting_observation_sum: float = 0.0
        self.pedestrian_waiting_observation_count: int = 0
        self.pedestrian_waiting_time_available: bool = True
        self.pedestrian_waiting_time_note: str = ""
        self.pedestrian_seen = set()
        self.pedestrian_waiting_count_max: int = 0
        self.pedestrian_speed_sum: float = 0.0
        self.pedestrian_speed_sample_count: int = 0
        self.pedestrian_controlled_crossing_persons_seen = set()
        self.pedestrian_tls_sensitive_persons_seen = set()
        self.pedestrian_edges_sample: List[str] = []
        self.pedestrian_controlled_crossing_waiting_time: float = 0.0
        self.pedestrian_metadata: Dict[str, object] = {}
        self.episode_queue_sum: float = 0.0
        self.episode_wait_sum: float = 0.0
        self.episode_total_waiting_time: float = 0.0
        self.cumulative_waiting_vehicle_seconds: float = 0.0
        self.sum_vehicle_waiting_time_samples: float = 0.0
        self.vehicle_waiting_time_sample_count: int = 0
        self.vehicles_seen = set()
        self.last_stats: Dict[str, dict] = {}
        self.phase_set_count: int = 0
        self.action_stats: Dict[str, object] = {}
        self.last_switch_actions_this_step = set()
        self.timing_profile = None
        self.timing_source: Dict[str, object] = {}
        self.program_set_count: int = 0
        self.last_reward_breakdown: Dict[str, object] = {}
        self._pedestrian_reward_warning_printed = False
        self.prev_waiting_sum_by_tls: Dict[str, float] = {}
        self.prev_queue_by_tls: Dict[str, float] = {}
        self.prev_waiting_avg_by_tls: Dict[str, float] = {}
        self.prev_pressure_abs_by_tls: Dict[str, float] = {}
        self.graph_building_seconds: float = 0.0
        self._cached_scenario = None
        self._cached_static_tls_key: Optional[Tuple[str, ...]] = None
        self._cached_num_phases_per_tls: Dict[str, int] = {}
        self._cached_incoming_lanes: Dict[str, List[str]] = {}
        self._cached_outgoing_lanes: Dict[str, List[str]] = {}
        self._vehicle_lane_cache: Dict[str, bool] = {}
        self._obs_stats = None

    def reset(self) -> Dict[str, np.ndarray]:
        self.close()
        self._start_sumo()
        self.sim_time = 0.0
        self.step_count = 0
        self.total_arrived = 0
        self.total_departed = 0
        self.pedestrian_departed_total = 0
        self.pedestrian_arrived_total = 0
        self.pedestrian_running_max = 0
        self.pedestrian_waiting_count_sum = 0
        self.pedestrian_waiting_observation_sum = 0.0
        self.pedestrian_waiting_observation_count = 0
        self.pedestrian_waiting_time_available = True
        self.pedestrian_waiting_time_note = ""
        self.pedestrian_seen = set()
        self.pedestrian_waiting_count_max = 0
        self.pedestrian_speed_sum = 0.0
        self.pedestrian_speed_sample_count = 0
        self.pedestrian_controlled_crossing_persons_seen = set()
        self.pedestrian_tls_sensitive_persons_seen = set()
        self.pedestrian_edges_sample = []
        self.pedestrian_controlled_crossing_waiting_time = 0.0
        self.episode_queue_sum = 0.0
        self.episode_wait_sum = 0.0
        self.episode_total_waiting_time = 0.0
        self.cumulative_waiting_vehicle_seconds = 0.0
        self.sum_vehicle_waiting_time_samples = 0.0
        self.vehicle_waiting_time_sample_count = 0
        self.vehicles_seen = set()
        self.phase_set_count = 0
        self.action_stats = self._new_action_stats()
        self.last_switch_actions_this_step = set()
        self.program_set_count = 0
        self.last_reward_breakdown = {}
        self._pedestrian_reward_warning_printed = False
        self.prev_waiting_sum_by_tls = {}
        self.prev_queue_by_tls = {}
        self.prev_waiting_avg_by_tls = {}
        self.prev_pressure_abs_by_tls = {}
        self._obs_stats = None

        self.all_tls_ids = list(self.traci.trafficlight.getIDList())
        self.tls_ids = self._select_controlled_tls(self.all_tls_ids)
        self.metric_tls_ids = self._select_metric_tls(self.all_tls_ids)
        self.smoke_total_tls_count = len(self.all_tls_ids)
        self.smoke_controlled_tls_count = len(self.tls_ids)
        if not self.tls_ids:
            raise RuntimeError(
                "В сценарии не найдено traffic light controllers. RL evaluation невозможен."
            )

        self._apply_real_timing_programs_if_needed()
        tls_key = tuple(self.tls_ids)
        if tls_key == self._cached_static_tls_key and self._cached_num_phases_per_tls:
            self.num_phases_per_tls = dict(self._cached_num_phases_per_tls)
        else:
            self.num_phases_per_tls = {tls_id: self._get_num_phases(tls_id) for tls_id in self.tls_ids}
            self._cached_num_phases_per_tls = dict(self.num_phases_per_tls)
        self.max_phases_global = max(1, max(self.num_phases_per_tls.values()))
        if self.obs_cfg is not None and hasattr(self.obs_cfg, "set_observation_phases"):
            self.obs_cfg.set_observation_phases(self.max_phases_global)
        self.obs_size = int(getattr(self.obs_cfg, "obs_base_size", 13)) + self.max_phases_global

        if tls_key == self._cached_static_tls_key and self._cached_incoming_lanes:
            self.incoming_lanes = {tls_id: list(lanes) for tls_id, lanes in self._cached_incoming_lanes.items()}
            self.outgoing_lanes = {tls_id: list(lanes) for tls_id, lanes in self._cached_outgoing_lanes.items()}
        else:
            self.incoming_lanes = {tls_id: self._get_incoming_lanes(tls_id) for tls_id in self.metric_tls_ids}
            self.outgoing_lanes = {tls_id: self._get_outgoing_lanes(tls_id) for tls_id in self.metric_tls_ids}
            self._cached_incoming_lanes = {tls_id: list(lanes) for tls_id, lanes in self.incoming_lanes.items()}
            self._cached_outgoing_lanes = {tls_id: list(lanes) for tls_id, lanes in self.outgoing_lanes.items()}
            self._cached_static_tls_key = tls_key
        self.last_phase_by_tls = {tls_id: self._get_phase(tls_id) for tls_id in self.tls_ids}
        self.time_since_switch_by_tls = {tls_id: 0.0 for tls_id in self.tls_ids}

        graph = self._get_cached_tls_graph()
        self.neighbors = {tls_id: [n for n in graph.get(tls_id, []) if n in self.tls_ids] for tls_id in self.tls_ids}

        self.last_stats = self._collect_all_stats()
        self.prev_waiting_sum_by_tls = {
            tls_id: float(stats.get("waiting_sum", 0.0)) for tls_id, stats in self.last_stats.items()
        }
        self.prev_queue_by_tls = {
            tls_id: float(stats.get("queue", 0.0)) for tls_id, stats in self.last_stats.items()
        }
        self.prev_waiting_avg_by_tls = {
            tls_id: float(stats.get("waiting_time", 0.0)) for tls_id, stats in self.last_stats.items()
        }
        self.prev_pressure_abs_by_tls = {
            tls_id: abs(float(stats.get("pressure", 0.0))) for tls_id, stats in self.last_stats.items()
        }
        return self._build_observations(self._controlled_stats(self.last_stats))

    def _get_cached_tls_graph(self) -> Dict[str, List[str]]:
        if not self.scenario or not self.scenario.net:
            return {}
        if (
            str(getattr(self.obs_cfg, "run_mode", "")).lower() in {"smoke", "fast", "validate_fast"}
            and bool(getattr(self.obs_cfg, "smoke_skip_tls_graph", True))
        ):
            return {}
        try:
            graph_key = str(Path(self.scenario.net).resolve())
        except Exception:
            graph_key = str(self.scenario.net)
        if graph_key in _GRAPH_CACHE:
            return _GRAPH_CACHE[graph_key]
        started = time.perf_counter()
        try:
            graph = build_tls_graph_from_net(
                self.scenario.net,
                debug=bool(getattr(self.obs_cfg, "debug_scenario", False)),
            )
        except Exception:
            graph = {}
        elapsed = float(time.perf_counter() - started)
        self.graph_building_seconds += elapsed
        global GRAPH_BUILDING_SECONDS_TOTAL
        GRAPH_BUILDING_SECONDS_TOTAL += elapsed
        _GRAPH_CACHE[graph_key] = graph
        return graph

    def step(self, actions_dict: Dict[str, int]) -> Tuple[Dict[str, np.ndarray], Dict[str, float], bool, dict]:
        if self.traci is None:
            raise RuntimeError("Окружение не запущено. Сначала вызовите reset().")

        self._apply_actions(actions_dict)
        self.traci.simulationStep()
        self.step_count += 1
        self.sim_time = float(self.traci.simulation.getTime())
        arrived_this_step = int(self.traci.simulation.getArrivedNumber())
        departed_this_step = int(self.traci.simulation.getDepartedNumber())
        self.total_arrived += arrived_this_step
        self.total_departed += departed_this_step
        departed_person_ids = self._get_person_event_ids("departed")
        arrived_person_ids = self._get_person_event_ids("arrived")
        if departed_person_ids is not None:
            self.pedestrian_departed_total += len(departed_person_ids)
            self.pedestrian_seen.update(departed_person_ids)
        else:
            self.pedestrian_departed_total += self._get_person_event_count("departed")
        if arrived_person_ids is not None:
            self.pedestrian_arrived_total += len(arrived_person_ids)
            self.pedestrian_seen.update(arrived_person_ids)
        else:
            self.pedestrian_arrived_total += self._get_person_event_count("arrived")

        self._update_phase_timers()
        stats = self._collect_all_stats()
        controlled_stats = self._controlled_stats(stats)
        pedestrian_metrics = self._collect_pedestrian_metrics()
        rewards = self._compute_rewards(
            controlled_stats,
            pedestrian_metrics,
            arrived_this_step=arrived_this_step,
        )
        observations = self._build_observations(controlled_stats)

        avg_queue = float(np.mean([s["queue"] for s in stats.values()])) if stats else 0.0
        avg_wait = float(np.mean([s["waiting_time"] for s in stats.values()])) if stats else 0.0
        step_total_waiting = float(sum(float(s.get("waiting_sum", 0.0)) for s in stats.values()))
        self.episode_queue_sum += avg_queue
        self.episode_wait_sum += avg_wait
        self.episode_total_waiting_time += step_total_waiting
        vehicle_metrics = self._collect_vehicle_network_metrics()
        self.cumulative_waiting_vehicle_seconds += (
            float(vehicle_metrics.get("halting_vehicle_count", 0.0)) * self.step_length
        )
        self.sum_vehicle_waiting_time_samples += float(
            vehicle_metrics.get("total_vehicle_waiting_time", 0.0)
        )
        self.vehicle_waiting_time_sample_count += int(
            vehicle_metrics.get("current_vehicle_count", 0)
        )
        for veh_id in vehicle_metrics.get("vehicle_ids", []):
            self.vehicles_seen.add(veh_id)

        try:
            sumo_finished = int(self.traci.simulation.getMinExpectedNumber()) <= 0
        except Exception:
            sumo_finished = False
        done = self.sim_time >= self.episode_seconds or sumo_finished
        try:
            loaded_this_step = int(self.traci.simulation.getLoadedNumber())
        except Exception:
            loaded_this_step = 0
        info = {
            "avg_queue": avg_queue,
            "avg_waiting_time": avg_wait,
            "total_waiting_time": self.episode_total_waiting_time,
            "legacy_total_waiting_time": self.episode_total_waiting_time,
            "cumulative_waiting_vehicle_seconds": self.cumulative_waiting_vehicle_seconds,
            "sum_vehicle_waiting_time_samples": self.sum_vehicle_waiting_time_samples,
            "final_total_waiting_time": vehicle_metrics["total_vehicle_waiting_time"],
            "avg_waiting_time_per_vehicle_sample": (
                self.sum_vehicle_waiting_time_samples
                / max(1, self.vehicle_waiting_time_sample_count)
            ),
            "vehicles_seen": len(self.vehicles_seen),
            "throughput": self.total_arrived,
            "departed": self.total_departed,
            "arrived": self.total_arrived,
            "loaded": loaded_this_step,
            "running": int(vehicle_metrics["current_vehicle_count"]),
            "current_vehicle_count": int(vehicle_metrics["current_vehicle_count"]),
            "phase_set_count": self.phase_set_count,
            "program_set_count": self.program_set_count,
            "action_stats": self.get_action_stats(),
            "timing_source": dict(self.timing_source),
            "avg_speed": vehicle_metrics["avg_speed"],
            "avg_time_loss": vehicle_metrics["avg_time_loss"],
            "total_time_loss": vehicle_metrics["total_time_loss"],
            "avg_distance": vehicle_metrics["avg_distance"],
            "total_distance": vehicle_metrics["total_distance"],
            "avg_vehicle_waiting_time": vehicle_metrics["avg_vehicle_waiting_time"],
            "total_vehicle_waiting_time": vehicle_metrics["total_vehicle_waiting_time"],
            "halting_vehicle_count": vehicle_metrics["halting_vehicle_count"],
            "vehicle_metrics_note": vehicle_metrics["note"],
            "mean_reward": float(np.mean(list(rewards.values()))) if rewards else 0.0,
            "episode_avg_queue": self.episode_queue_sum / max(1, self.step_count),
            "episode_avg_waiting_time": self.episode_wait_sum / max(1, self.step_count),
            "sim_time": self.sim_time,
            "reward_breakdown": dict(self.last_reward_breakdown),
            "avg_vehicle_reward_component": float(
                self.last_reward_breakdown.get("avg_vehicle_reward_component", 0.0)
            ),
            "avg_pedestrian_reward_component": float(
                self.last_reward_breakdown.get("avg_pedestrian_reward_component", 0.0)
            ),
            "pedestrian_reward_share": float(
                self.last_reward_breakdown.get("pedestrian_reward_share", 0.0)
            ),
        }
        info.update(pedestrian_metrics)
        self.last_stats = stats
        return observations, rewards, done, info

    def close(self) -> None:
        self._save_observation_stats()
        if self.conn is not None:
            try:
                self.conn.close(False)
            except TypeError:
                try:
                    self.conn.close()
                except Exception:
                    pass
            except Exception:
                pass
        self.conn = None
        self.traci = None

    def _start_sumo(self) -> None:
        add_sumo_tools_to_path()
        try:
            import traci
        except Exception as exc:
            raise RuntimeError(
                "Python не может импортировать traci. Проверьте SUMO_HOME и SUMO_HOME/tools."
            ) from exc

        if self._cached_scenario is None:
            self._cached_scenario = discover_scenario(
                self.scenario_dir,
                begin=0.0,
                end=float(self.episode_seconds),
                step_length=self.step_length,
                auto_generate_sumocfg=True,
                scenario_sumocfg_file=getattr(self.obs_cfg, "scenario_sumocfg_file", None),
                scenario_net_file=getattr(self.obs_cfg, "scenario_net_file", None),
                scenario_route_file=getattr(self.obs_cfg, "scenario_route_file", None),
                auto_generate_pedestrians_if_missing=bool(
                    getattr(self.obs_cfg, "auto_generate_pedestrians_if_missing", False)
                ),
                pedestrian_count=int(getattr(self.obs_cfg, "pedestrian_demand_count", 30)),
                pedestrian_begin=int(getattr(self.obs_cfg, "pedestrian_demand_begin", 0)),
                pedestrian_end=int(getattr(self.obs_cfg, "pedestrian_demand_end", self.episode_seconds)),
                pedestrian_prefix=str(getattr(self.obs_cfg, "pedestrian_demand_prefix", "auto_ped")),
                pedestrian_mode=str(getattr(self.obs_cfg, "pedestrian_mode", "crossing_focused")),
                real_timing_file_name=str(getattr(self.obs_cfg, "real_timing_file", "tls.add.xml")),
                rl_use_real_timing_program_as_base=bool(
                    getattr(self.obs_cfg, "rl_use_real_timing_program_as_base", True)
                ),
                scenario_preferred_prefix=str(getattr(self.obs_cfg, "scenario_preferred_prefix", "kaliningrad")),
                allow_mixed_scenario_files=bool(
                    getattr(self.obs_cfg, "allow_mixed_scenario_files", False)
                ),
                preferred_controlled_tls_ids=getattr(self.obs_cfg, "preferred_controlled_tls_ids", None),
            )
        self.scenario = self._cached_scenario
        self.pedestrian_metadata = self._load_pedestrian_metadata()
        if not self.scenario.found or not self.scenario.sumocfg:
            raise RuntimeError("В scenario/ нужны *.sumocfg или net.xml (*.net.xml) и route-файлы (*.rou.xml/*.trips.xml).")

        extra_args = self.sumo_extra_args
        if extra_args is None:
            extra_args = [
                "--no-step-log",
                "true",
                "--quit-on-end",
                "true",
                "--time-to-teleport",
                "-1",
                "--duration-log.disable",
                "true",
                "--waiting-time-memory",
                str(max(1000, self.episode_seconds + 100)),
            ]
        cmd = build_sumo_command(
            self.scenario,
            use_gui=self.use_gui,
            seed=self.seed,
            step_length=self.step_length,
            extra_args=extra_args,
            end=float(self.episode_seconds),
            mode=self.mode,
        )
        if not self.use_gui:
            cmd.extend(["--no-warnings", "true"])

        try:
            num_retries = 30 if str(getattr(self.obs_cfg, "run_mode", "")).lower() == "smoke" else 60
            try:
                traci.start(cmd, label=self.label, numRetries=num_retries)
            except TypeError:
                traci.start(cmd, label=self.label)
            self.conn = traci.getConnection(self.label)
            self.traci = self.conn
        except Exception as exc:
            raise RuntimeError(f"SUMO/TraCI не смог запустить сценарий: {exc}") from exc

    def _mode_uses_real_timing(self) -> bool:
        return self.mode == "real_timing" or (
            self.mode == "rl"
            and bool(getattr(self.obs_cfg, "rl_use_real_timing_program_as_base", True))
        )

    def _load_pedestrian_metadata(self) -> Dict[str, object]:
        metadata = dict(getattr(self.scenario, "pedestrian_metadata", {}) or {})
        if metadata:
            return metadata
        try:
            scenario_dir = Path(getattr(self.scenario, "scenario_dir", self.scenario_dir))
            path = scenario_dir / AUTOGENERATED_PEDESTRIANS_META
            if path.exists():
                data = json.loads(path.read_text(encoding="utf-8"))
                return data if isinstance(data, dict) else {}
        except Exception:
            return {}
        return {}

    def _apply_real_timing_programs_if_needed(self) -> None:
        path = getattr(self.scenario, "real_timing_file", None) if self.scenario else None
        source = {
            "file": str(path) if path else None,
            "mode": self.mode,
            "programs_loaded": 0,
            "tls_with_real_timing": [],
            "tls_without_real_timing": list(self.tls_ids),
            "tls_missing_in_network": [],
            "program_set_count": 0,
            "active_programs": {},
            "phase_count_check": {},
            "phase_duration_check": {},
            "used_in_this_mode": False,
        }
        if not path:
            self.timing_source = source
            return
        if not self._mode_uses_real_timing():
            self.timing_source = source
            return
        try:
            self.timing_profile = load_timing_profile(path)
        except Exception as exc:
            source["error"] = str(exc)
            self.timing_source = source
            return

        programs = self.timing_profile.programs
        source["programs_loaded"] = len(programs)
        tls_set = set(self.tls_ids)
        with_timing = [tls_id for tls_id in self.tls_ids if tls_id in programs]
        source["tls_with_real_timing"] = with_timing
        source["tls_without_real_timing"] = [tls_id for tls_id in self.tls_ids if tls_id not in programs]
        source["tls_missing_in_network"] = [tls_id for tls_id in programs if tls_id not in tls_set]

        source["used_in_this_mode"] = True
        for tls_id in with_timing:
            program = programs[tls_id]
            try:
                current_program = str(self.traci.trafficlight.getProgram(tls_id))
            except Exception:
                current_program = ""
            if program.programID and current_program != program.programID:
                try:
                    self.traci.trafficlight.setProgram(tls_id, program.programID)
                    self.program_set_count += 1
                    current_program = str(self.traci.trafficlight.getProgram(tls_id))
                except Exception as exc:
                    source.setdefault("program_set_errors", {})[tls_id] = str(exc)
            source["active_programs"][tls_id] = current_program
            phase_durations = self._active_phase_durations(tls_id)
            source["phase_count_check"][tls_id] = {
                "expected": len(program.phases),
                "actual": len(phase_durations),
                "matches": len(program.phases) == len(phase_durations),
            }
            source["phase_duration_check"][tls_id] = {
                "expected": [phase.duration for phase in program.phases],
                "actual": phase_durations,
                "matches": len(phase_durations) == len(program.phases)
                and all(
                    abs(float(a) - float(b.duration)) <= 1e-6
                    for a, b in zip(phase_durations, program.phases)
                ),
            }
        source["program_set_count"] = self.program_set_count
        self.timing_source = source

    def _active_program_logic(self, tls_id: str):
        try:
            active_program = str(self.traci.trafficlight.getProgram(tls_id))
        except Exception:
            active_program = ""
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", UserWarning)
                logics = self.traci.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)
            if logics:
                for logic in logics:
                    if str(getattr(logic, "programID", "")) == active_program:
                        return logic
                return logics[0]
        except Exception:
            pass
        try:
            logics = self.traci.trafficlight.getAllProgramLogics(tls_id)
            if logics:
                for logic in logics:
                    if str(getattr(logic, "programID", "")) == active_program:
                        return logic
                return logics[0]
        except Exception:
            pass
        return None

    def _active_phase_durations(self, tls_id: str) -> List[float]:
        logic = self._active_program_logic(tls_id)
        if logic is not None:
            return [float(getattr(phase, "duration", 0.0)) for phase in logic.phases]
        return []

    def _get_num_phases(self, tls_id: str) -> int:
        try:
            logic = self._active_program_logic(tls_id)
            if logic is not None:
                return max(1, len(logic.phases))
        except Exception:
            pass
        try:
            logics = self.traci.trafficlight.getAllProgramLogics(tls_id)
            if logics:
                return max(1, len(logics[0].phases))
        except Exception:
            pass
        try:
            state = self.traci.trafficlight.getRedYellowGreenState(tls_id)
            return 1 if state else 1
        except Exception:
            return 1

    def _get_phase_states(self, tls_id: str) -> List[str]:
        try:
            logic = self._active_program_logic(tls_id)
            if logic is not None:
                return [str(phase.state) for phase in logic.phases]
        except Exception:
            pass
        return []

    def _get_phase(self, tls_id: str) -> int:
        try:
            return int(self.traci.trafficlight.getPhase(tls_id))
        except Exception:
            return 0

    def _get_incoming_lanes(self, tls_id: str) -> List[str]:
        lanes = []
        try:
            lanes.extend(self.traci.trafficlight.getControlledLanes(tls_id))
        except Exception:
            pass

        if not lanes:
            try:
                controlled_links = self.traci.trafficlight.getControlledLinks(tls_id)
                for signal_links in controlled_links:
                    for link in signal_links:
                        if link and link[0]:
                            lanes.append(link[0])
            except Exception:
                pass

        result = []
        seen = set()
        for lane_id in lanes:
            if lane_id in seen:
                continue
            seen.add(lane_id)
            if self._is_vehicle_lane(lane_id):
                result.append(lane_id)
        return result

    def _get_outgoing_lanes(self, tls_id: str) -> List[str]:
        lanes = []
        try:
            controlled_links = self.traci.trafficlight.getControlledLinks(tls_id)
            for signal_links in controlled_links:
                for link in signal_links:
                    if len(link) > 1 and link[1]:
                        lanes.append(link[1])
        except Exception:
            lanes = []

        result = []
        seen = set()
        for lane_id in lanes:
            if lane_id in seen:
                continue
            seen.add(lane_id)
            if self._is_vehicle_lane(lane_id):
                result.append(lane_id)
        return result

    def _is_vehicle_lane(self, lane_id: str) -> bool:
        if lane_id in self._vehicle_lane_cache:
            return self._vehicle_lane_cache[lane_id]
        if not lane_id or lane_id.startswith(":"):
            self._vehicle_lane_cache[lane_id] = False
            return False
        try:
            allowed = set(self.traci.lane.getAllowed(lane_id))
            if allowed and allowed.issubset(PEDESTRIAN_ONLY_CLASSES):
                self._vehicle_lane_cache[lane_id] = False
                return False
            if allowed and not allowed.intersection(VEHICLE_CLASSES):
                self._vehicle_lane_cache[lane_id] = False
                return False
        except Exception:
            self._vehicle_lane_cache[lane_id] = False
            return False

        try:
            edge_id = self.traci.lane.getEdgeID(lane_id)
            if "walkingarea" in edge_id.lower() or "crossing" in edge_id.lower():
                self._vehicle_lane_cache[lane_id] = False
                return False
        except Exception:
            pass

        self._vehicle_lane_cache[lane_id] = True
        return True

    def _select_controlled_tls(self, tls_ids: List[str]) -> List[str]:
        tls_ids = list(tls_ids)
        preferred = list(getattr(self.obs_cfg, "preferred_controlled_tls_ids", None) or [])
        configured_limit = getattr(self.obs_cfg, "max_controlled_tls", None)
        limit = int(configured_limit or 0)
        if limit <= 0 and str(getattr(self.obs_cfg, "run_mode", "")).lower() == "smoke":
            limit = int(getattr(self.obs_cfg, "smoke_max_controlled_tls", 0) or 0)
        if preferred:
            selected = [tls_id for tls_id in preferred if tls_id in tls_ids]
            target_limit = limit if limit > 0 else len(selected)
            if len(selected) < target_limit:
                for tls_id in tls_ids:
                    if tls_id not in selected and self._get_incoming_lanes(tls_id):
                        selected.append(tls_id)
                    if len(selected) >= target_limit:
                        break
            return selected[:target_limit] if target_limit > 0 else selected
        if limit <= 0 and str(getattr(self.obs_cfg, "run_mode", "")).lower() != "smoke":
            return tls_ids
        if limit <= 0 or len(tls_ids) <= limit:
            return tls_ids

        selected = []
        for tls_id in tls_ids:
            if self._get_incoming_lanes(tls_id):
                selected.append(tls_id)
            if len(selected) >= limit:
                break
        if len(selected) < limit:
            for tls_id in tls_ids:
                if tls_id not in selected:
                    selected.append(tls_id)
                if len(selected) >= limit:
                    break
        return selected

    def _select_metric_tls(self, tls_ids: List[str]) -> List[str]:
        tls_ids = list(tls_ids)
        run_mode = str(getattr(self.obs_cfg, "run_mode", "")).lower()
        if run_mode in {"smoke", "fast", "validate_fast"}:
            return list(self.tls_ids) or tls_ids
        if run_mode != "smoke":
            return tls_ids
        selected = [tls_id for tls_id in tls_ids if self._get_incoming_lanes(tls_id)]
        return selected or tls_ids

    def _new_action_stats(self) -> dict:
        return {
            "decision_count": 0,
            "hold_count": 0,
            "switch_count": 0,
            "blocked_by_min_green_count": 0,
            "phase_set_count": 0,
            "hold_phase_set_count": 0,
            "switch_phase_set_count": 0,
            "per_tls": {},
        }

    def _ensure_tls_action_stats(self, tls_id: str) -> dict:
        per_tls = self.action_stats.setdefault("per_tls", {})
        if tls_id not in per_tls:
            per_tls[tls_id] = {
                "hold": 0,
                "switch": 0,
                "blocked_by_min_green_count": 0,
                "phase_set_count": 0,
                "hold_phase_set_count": 0,
                "switch_phase_set_count": 0,
            }
        return per_tls[tls_id]

    def get_action_stats(self) -> dict:
        return {
            "decision_count": int(self.action_stats.get("decision_count", 0)),
            "hold_count": int(self.action_stats.get("hold_count", 0)),
            "switch_count": int(self.action_stats.get("switch_count", 0)),
            "blocked_by_min_green_count": int(
                self.action_stats.get("blocked_by_min_green_count", 0)
            ),
            "phase_set_count": int(self.action_stats.get("phase_set_count", 0)),
            "hold_phase_set_count": int(self.action_stats.get("hold_phase_set_count", 0)),
            "switch_phase_set_count": int(self.action_stats.get("switch_phase_set_count", 0)),
            "per_tls": {
                tls_id: dict(values)
                for tls_id, values in self.action_stats.get("per_tls", {}).items()
            },
        }

    def _apply_actions(self, actions_dict: Dict[str, int]) -> None:
        self.last_switch_actions_this_step = set()
        interval = max(
            1,
            int(
                getattr(
                    self.obs_cfg,
                    "control_decision_interval",
                    getattr(self.obs_cfg, "decision_interval", params.CONTROL_DECISION_INTERVAL),
                )
            ),
        )
        if self.step_count % interval != 0:
            return
        for tls_id in self.tls_ids:
            if tls_id not in actions_dict:
                continue
            action = int(actions_dict.get(tls_id, 0))
            tls_stats = self._ensure_tls_action_stats(tls_id)
            self.action_stats["decision_count"] += 1
            if action != 1:
                self.action_stats["hold_count"] += 1
                tls_stats["hold"] += 1
                continue
            self.action_stats["switch_count"] += 1
            tls_stats["switch"] += 1
            num_phases = self.num_phases_per_tls.get(tls_id, 1)
            if num_phases <= 1:
                continue
            if self.time_since_switch_by_tls.get(tls_id, 0.0) < self.min_green:
                self.action_stats["blocked_by_min_green_count"] += 1
                tls_stats["blocked_by_min_green_count"] += 1
                continue
            current_phase = self._get_phase(tls_id)
            next_phase = self._next_green_phase(tls_id, current_phase, num_phases)
            try:
                self.traci.trafficlight.setPhase(tls_id, next_phase)
                self.phase_set_count += 1
                self.action_stats["phase_set_count"] += 1
                self.action_stats["switch_phase_set_count"] = (
                    int(self.action_stats.get("switch_phase_set_count", 0)) + 1
                )
                tls_stats["phase_set_count"] += 1
                tls_stats["switch_phase_set_count"] += 1
                self.last_switch_actions_this_step.add(tls_id)
                self.last_phase_by_tls[tls_id] = next_phase
                self.time_since_switch_by_tls[tls_id] = 0.0
            except Exception:
                continue

    def _next_green_phase(self, tls_id: str, current_phase: int, num_phases: int) -> int:
        phase_states = self._get_phase_states(tls_id)
        if not phase_states:
            return (current_phase + 1) % max(1, num_phases)
        for offset in range(1, max(1, num_phases) + 1):
            candidate = (current_phase + offset) % max(1, num_phases)
            state = phase_states[candidate] if candidate < len(phase_states) else ""
            if self._is_green_phase_state(state):
                return candidate
        return (current_phase + 1) % max(1, num_phases)

    @staticmethod
    def _is_green_phase_state(state: str) -> bool:
        return ("g" in state.lower()) and ("y" not in state.lower())

    def _update_phase_timers(self) -> None:
        for tls_id in self.tls_ids:
            current_phase = self._get_phase(tls_id)
            last_phase = self.last_phase_by_tls.get(tls_id, current_phase)
            if current_phase != last_phase:
                self.last_phase_by_tls[tls_id] = current_phase
                self.time_since_switch_by_tls[tls_id] = 0.0
            else:
                self.time_since_switch_by_tls[tls_id] = self.time_since_switch_by_tls.get(tls_id, 0.0) + self.step_length

    def _collect_all_stats(self) -> Dict[str, dict]:
        return {tls_id: self._collect_local_stats(tls_id) for tls_id in self.metric_tls_ids}

    def _controlled_stats(self, stats: Dict[str, dict]) -> Dict[str, dict]:
        return {tls_id: stats[tls_id] for tls_id in self.tls_ids if tls_id in stats}

    def _get_person_event_count(self, event: str) -> int:
        if event == "departed":
            list_methods = ("getDepartedPersonIDList", "getDepartedPersonIDs")
            number_methods = ("getDepartedPersonNumber",)
        else:
            list_methods = ("getArrivedPersonIDList", "getArrivedPersonIDs")
            number_methods = ("getArrivedPersonNumber",)

        for method_name in list_methods:
            try:
                method = getattr(self.traci.simulation, method_name)
                return len(list(method()))
            except Exception:
                pass
        for method_name in number_methods:
            try:
                method = getattr(self.traci.simulation, method_name)
                return int(method())
            except Exception:
                pass
        return 0

    def _get_person_event_ids(self, event: str) -> Optional[List[str]]:
        if event == "departed":
            list_methods = ("getDepartedPersonIDList", "getDepartedPersonIDs")
        else:
            list_methods = ("getArrivedPersonIDList", "getArrivedPersonIDs")
        for method_name in list_methods:
            try:
                method = getattr(self.traci.simulation, method_name)
                return [str(item) for item in method()]
            except Exception:
                pass
        return None

    def _collect_pedestrian_metrics(self) -> dict:
        running_ids = []
        waiting_values = []
        fallback_waiting_count = 0
        controlled_waiting_this_step = 0.0
        speed_values = []
        tls_sensitive_ids = set(self.pedestrian_metadata.get("tls_sensitive_person_ids", []) or [])
        tls_sensitive_edges = set(self.pedestrian_metadata.get("tls_sensitive_edges", []) or [])
        controlled_tls_person_ids = set(self.pedestrian_metadata.get("controlled_tls_sensitive_person_ids", []) or [])
        controlled_tls_edges = set(self.pedestrian_metadata.get("controlled_tls_overlap_edges", []) or [])

        try:
            running_ids = [str(person_id) for person_id in self.traci.person.getIDList()]
        except Exception:
            running_ids = []
            self.pedestrian_waiting_time_available = False
            self.pedestrian_waiting_time_note = (
                "TraCI person domain is not available in this SUMO version."
            )

        self.pedestrian_seen.update(running_ids)
        self.pedestrian_running_max = max(self.pedestrian_running_max, len(running_ids))

        for person_id in running_ids:
            waiting_value = None
            speed_value = None
            edge_id = ""
            try:
                waiting_value = float(self.traci.person.getWaitingTime(person_id))
                waiting_values.append(waiting_value)
            except Exception:
                self.pedestrian_waiting_time_available = False
                self.pedestrian_waiting_time_note = (
                    "TraCI person waiting time is not available in this SUMO version."
                )
            try:
                speed_value = float(self.traci.person.getSpeed(person_id))
                speed_values.append(speed_value)
                if waiting_value is None and speed_value < 0.1:
                    fallback_waiting_count += 1
            except Exception:
                speed_value = None
            try:
                edge_id = str(self.traci.person.getRoadID(person_id))
            except Exception:
                try:
                    edge_id = str(self.traci.person.getNextEdge(person_id))
                except Exception:
                    edge_id = ""
            if edge_id and len(self.pedestrian_edges_sample) < 20 and edge_id not in self.pedestrian_edges_sample:
                self.pedestrian_edges_sample.append(edge_id)
            is_tls_sensitive = person_id in tls_sensitive_ids or (edge_id and edge_id in tls_sensitive_edges)
            is_controlled_tls_sensitive = (
                person_id in controlled_tls_person_ids
                or (edge_id and edge_id in controlled_tls_edges)
            )
            if is_tls_sensitive:
                self.pedestrian_tls_sensitive_persons_seen.add(person_id)
            if is_controlled_tls_sensitive:
                self.pedestrian_controlled_crossing_persons_seen.add(person_id)
                controlled_waiting_this_step += float(waiting_value or 0.0)

        if speed_values:
            self.pedestrian_speed_sum += float(sum(speed_values))
            self.pedestrian_speed_sample_count += len(speed_values)

        if self.pedestrian_waiting_time_available:
            waiting_count = sum(1 for value in waiting_values if value > 0.0)
            self.pedestrian_waiting_count_sum += int(waiting_count)
            self.pedestrian_waiting_observation_sum += float(sum(waiting_values))
            self.pedestrian_waiting_observation_count += len(waiting_values)
            total_waiting = float(self.pedestrian_waiting_observation_sum)
            avg_waiting = total_waiting / max(1, self.pedestrian_waiting_observation_count)
            note = ""
        else:
            waiting_count = fallback_waiting_count
            self.pedestrian_waiting_count_sum += int(waiting_count)
            self.pedestrian_waiting_observation_sum += float(waiting_count) * float(self.step_length)
            self.pedestrian_waiting_observation_count += len(running_ids)
            total_waiting = float(self.pedestrian_waiting_observation_sum)
            avg_waiting = total_waiting / max(1, self.pedestrian_waiting_observation_count)
            note = (
                self.pedestrian_waiting_time_note
                or "TraCI person waiting time unavailable; using speed < 0.1 fallback."
            )
        self.pedestrian_waiting_count_max = max(self.pedestrian_waiting_count_max, int(waiting_count or 0))
        self.pedestrian_controlled_crossing_waiting_time += controlled_waiting_this_step
        avg_speed = self.pedestrian_speed_sum / max(1, self.pedestrian_speed_sample_count)
        arrival_rate = self.pedestrian_arrived_total / max(1, self.pedestrian_departed_total)
        metadata_count = int(self.pedestrian_metadata.get("actual_persons", 0) or 0)
        persons_loaded = max(
            metadata_count,
            self.pedestrian_departed_total,
            self.pedestrian_arrived_total + len(running_ids),
            len(self.pedestrian_seen),
        )
        warning = str(self.pedestrian_metadata.get("warning", "") or "")
        if not warning and metadata_count and not self.pedestrian_tls_sensitive_persons_seen:
            warning = "No TLS-sensitive pedestrians observed yet; pedestrian metrics may be identical on short runs."
        controlled_overlap_count = int(
            self.pedestrian_metadata.get("controlled_tls_overlap_count", len(controlled_tls_edges)) or 0
        )
        if (
            not warning
            and metadata_count
            and controlled_tls_person_ids
            and not self.pedestrian_controlled_crossing_persons_seen
        ):
            warning = "No pedestrians observed on selected controlled TLS yet; pedestrian metrics may match fixed-time."
        diagnostics = {
            "persons_loaded": persons_loaded,
            "persons_departed": self.pedestrian_departed_total,
            "persons_arrived": self.pedestrian_arrived_total,
            "persons_running": len(running_ids),
            "persons_seen": len(self.pedestrian_seen),
            "waiting_samples": self.pedestrian_waiting_observation_count,
            "speed_samples": self.pedestrian_speed_sample_count,
            "controlled_crossing_persons_seen": len(self.pedestrian_controlled_crossing_persons_seen),
            "tls_sensitive_persons_seen": len(self.pedestrian_tls_sensitive_persons_seen),
            "controlled_tls_sensitive_persons_seen": len(self.pedestrian_controlled_crossing_persons_seen),
            "controlled_tls_sensitive_routes": int(
                self.pedestrian_metadata.get("controlled_tls_sensitive_routes", 0) or 0
            ),
            "controlled_tls_overlap_edges_count": controlled_overlap_count,
            "pedestrian_signal_link_count": int(
                self.pedestrian_metadata.get("pedestrian_signal_link_count", 0) or 0
            ),
            "controlled_tls_ids": list(self.pedestrian_metadata.get("controlled_tls_ids", []) or [])[:20],
            "controlled_tls_overlap_edges_sample": list(controlled_tls_edges)[:20],
            "pedestrian_routes_count": metadata_count,
            "pedestrian_edges_sample": list(self.pedestrian_edges_sample)[:20],
            "warning": warning,
        }

        return {
            "pedestrian_departed": self.pedestrian_departed_total,
            "pedestrian_arrived": self.pedestrian_arrived_total,
            "pedestrian_running": len(running_ids),
            "pedestrian_seen": len(self.pedestrian_seen),
            "pedestrian_running_max": self.pedestrian_running_max,
            "pedestrian_waiting_count": waiting_count,
            "pedestrian_waiting_count_avg": (
                self.pedestrian_waiting_count_sum / max(1, self.step_count)
            ),
            "pedestrian_waiting_count_max": self.pedestrian_waiting_count_max,
            "pedestrian_waiting_count_sum": (
                self.pedestrian_waiting_count_sum if self.pedestrian_waiting_time_available else None
            ),
            "pedestrian_total_waiting_time": total_waiting,
            "pedestrian_total_waiting_time_samples": total_waiting,
            "pedestrian_avg_waiting_time": avg_waiting,
            "pedestrian_avg_waiting_time_sampled": avg_waiting,
            "pedestrian_avg_speed": avg_speed,
            "pedestrian_arrival_rate": arrival_rate,
            "pedestrian_time_loss_approx": total_waiting,
            "pedestrian_tls_sensitive_seen": len(self.pedestrian_tls_sensitive_persons_seen),
            "pedestrian_controlled_crossing_waiting_time": self.pedestrian_controlled_crossing_waiting_time,
            "pedestrian_waiting_time_available": self.pedestrian_waiting_time_available,
            "pedestrian_waiting_time_note": note,
            "pedestrian_diagnostics": diagnostics,
        }

    def _collect_vehicle_network_metrics(self) -> dict:
        try:
            vehicle_ids = list(self.traci.vehicle.getIDList())
        except Exception:
            vehicle_ids = []

        speeds = []
        time_losses = []
        distances = []
        waiting_times = []
        halting_count = 0
        notes = []
        for veh_id in vehicle_ids:
            try:
                speeds.append(float(self.traci.vehicle.getSpeed(veh_id)))
            except Exception:
                pass
            try:
                waiting_time = float(self.traci.vehicle.getWaitingTime(veh_id))
                waiting_times.append(waiting_time)
                if waiting_time > 0.0:
                    halting_count += 1
            except Exception as exc:
                if "waiting_time" not in notes:
                    notes.append("waiting_time unavailable")
            try:
                time_losses.append(float(self.traci.vehicle.getTimeLoss(veh_id)))
            except Exception:
                if "time_loss unavailable" not in notes:
                    notes.append("time_loss unavailable")
            try:
                distances.append(float(self.traci.vehicle.getDistance(veh_id)))
            except Exception:
                if "distance unavailable" not in notes:
                    notes.append("distance unavailable")

        return {
            "avg_speed": float(np.mean(speeds)) if speeds else 0.0,
            "avg_time_loss": float(np.mean(time_losses)) if time_losses else 0.0,
            "total_time_loss": float(np.sum(time_losses)) if time_losses else 0.0,
            "avg_distance": float(np.mean(distances)) if distances else 0.0,
            "total_distance": float(np.sum(distances)) if distances else 0.0,
            "avg_vehicle_waiting_time": float(np.mean(waiting_times)) if waiting_times else 0.0,
            "total_vehicle_waiting_time": float(np.sum(waiting_times)) if waiting_times else 0.0,
            "halting_vehicle_count": int(halting_count),
            "current_vehicle_count": int(len(vehicle_ids)),
            "vehicle_ids": list(vehicle_ids),
            "note": "; ".join(notes),
        }

    def _collect_local_stats(self, tls_id: str) -> dict:
        lanes = self.incoming_lanes.get(tls_id, [])
        outgoing_lanes = self.outgoing_lanes.get(tls_id, [])
        queue = 0.0
        wait_sum = 0.0
        vehicle_count = 0.0
        outgoing_vehicle_count = 0.0
        speed_values = []
        time_loss_sum = 0.0

        for lane_id in lanes:
            try:
                queue += float(self.traci.lane.getLastStepHaltingNumber(lane_id))
            except Exception:
                continue
            try:
                vehicle_ids = list(self.traci.lane.getLastStepVehicleIDs(lane_id))
            except Exception:
                vehicle_ids = []
            vehicle_count += float(len(vehicle_ids))
            for veh_id in vehicle_ids:
                try:
                    wait_sum += float(self.traci.vehicle.getWaitingTime(veh_id))
                except Exception:
                    continue
                try:
                    speed_values.append(float(self.traci.vehicle.getSpeed(veh_id)))
                except Exception:
                    pass
                try:
                    time_loss_sum += float(self.traci.vehicle.getTimeLoss(veh_id))
                except Exception:
                    pass

        for lane_id in outgoing_lanes:
            try:
                outgoing_vehicle_count += float(self.traci.lane.getLastStepVehicleNumber(lane_id))
            except Exception:
                try:
                    outgoing_vehicle_count += float(len(self.traci.lane.getLastStepVehicleIDs(lane_id)))
                except Exception:
                    pass

        waiting_time = wait_sum / max(1.0, vehicle_count)
        phase = self._get_phase(tls_id)
        pressure = vehicle_count - outgoing_vehicle_count
        return {
            "queue": queue,
            "waiting_time": waiting_time,
            "waiting_sum": wait_sum,
            "vehicle_count": vehicle_count,
            "incoming_vehicle_count": vehicle_count,
            "outgoing_vehicle_count": outgoing_vehicle_count,
            "pressure": pressure,
            "pressure_abs": abs(pressure),
            "phase_pressure": pressure if self._phase_is_green(tls_id, phase) else 0.0,
            "avg_speed": float(np.mean(speed_values)) if speed_values else 0.0,
            "time_loss_sum": time_loss_sum,
            "current_phase_index": phase,
            "time_since_switch": self.time_since_switch_by_tls.get(tls_id, 0.0),
            "num_phases": self.num_phases_per_tls.get(tls_id, 1),
            "num_lanes": len(lanes),
        }

    def _phase_is_green(self, tls_id: str, phase: int) -> bool:
        states = self._get_phase_states(tls_id)
        if not states or phase >= len(states):
            return True
        return self._is_green_phase_state(states[phase])

    def _compute_rewards(
        self,
        stats: Dict[str, dict],
        pedestrian_metrics: Optional[dict] = None,
        arrived_this_step: int = 0,
    ) -> Dict[str, float]:
        rewards = {}
        reward_variant = str(
            getattr(self.obs_cfg, "reward_variant", params.REWARD_VARIANT)
        ).strip().lower()
        queue_norm = max(
            1e-6,
            float(getattr(self.obs_cfg, "reward_queue_norm", getattr(self.obs_cfg, "queue_norm", params.QUEUE_NORM))),
        )
        wait_norm = max(
            1e-6,
            float(getattr(self.obs_cfg, "reward_wait_norm", getattr(self.obs_cfg, "waiting_norm", params.WAIT_NORM))),
        )
        pressure_norm = max(1e-6, float(getattr(self.obs_cfg, "reward_pressure_norm", params.REWARD_PRESSURE_NORM)))
        time_loss_norm = max(1e-6, float(getattr(self.obs_cfg, "reward_time_loss_norm", params.REWARD_TIME_LOSS_NORM)))
        w_pressure_improvement = float(getattr(self.obs_cfg, "w_pressure_improvement", params.W_PRESSURE_IMPROVEMENT))
        w_queue_improvement = float(getattr(self.obs_cfg, "w_queue_improvement", params.W_QUEUE_IMPROVEMENT))
        w_wait_improvement = float(getattr(self.obs_cfg, "w_wait_improvement", params.W_WAIT_IMPROVEMENT))
        w_queue_level = float(getattr(self.obs_cfg, "w_queue_level", params.W_QUEUE_LEVEL))
        w_wait_level = float(getattr(self.obs_cfg, "w_wait_level", params.W_WAIT_LEVEL))
        w_time_loss = float(getattr(self.obs_cfg, "w_time_loss", params.W_TIME_LOSS))
        w_neighbor = float(getattr(self.obs_cfg, "w_neighbor", params.W_NEIGHBOR))
        throughput_weight = float(getattr(self.obs_cfg, "reward_throughput_weight", 0.0))
        use_throughput_bonus = bool(getattr(self.obs_cfg, "reward_use_throughput_bonus", False))
        pedestrian_penalty = self._compute_pedestrian_reward_penalty(pedestrian_metrics or {})
        per_tls_breakdown = {}
        for tls_id, local in stats.items():
            lane_count = max(1.0, float(local.get("num_lanes", 1.0)))
            queue_per_lane = float(local.get("queue", 0.0)) / lane_count
            queue_level = queue_per_lane / queue_norm
            wait_level = float(local.get("waiting_time", 0.0)) / wait_norm
            pressure_abs = abs(float(local.get("pressure", 0.0)))
            pressure_abs_norm = pressure_abs / pressure_norm
            time_loss_level = (
                float(local.get("time_loss_sum", 0.0)) / lane_count / time_loss_norm
            )
            wait_sum = float(local.get("waiting_sum", 0.0))
            prev_wait_sum = float(self.prev_waiting_sum_by_tls.get(tls_id, wait_sum))
            delta_wait = wait_sum - prev_wait_sum
            prev_queue = float(self.prev_queue_by_tls.get(tls_id, float(local.get("queue", 0.0))))
            prev_wait_avg = float(self.prev_waiting_avg_by_tls.get(tls_id, float(local.get("waiting_time", 0.0))))
            prev_pressure_abs = float(self.prev_pressure_abs_by_tls.get(tls_id, pressure_abs))
            queue_improvement = (prev_queue - float(local.get("queue", 0.0))) / queue_norm
            wait_improvement = (prev_wait_avg - float(local.get("waiting_time", 0.0))) / wait_norm
            pressure_improvement = (prev_pressure_abs - pressure_abs) / pressure_norm
            neighbor_terms = []
            for neighbor_id in self.neighbors.get(tls_id, []):
                if neighbor_id in stats:
                    n = stats[neighbor_id]
                    n_lanes = max(1.0, float(n.get("num_lanes", 1.0)))
                    neighbor_terms.append(
                        ((float(n.get("queue", 0.0)) / n_lanes) / queue_norm)
                        + (float(n.get("waiting_time", 0.0)) / wait_norm)
                    )
            neighbor_mean = sum(neighbor_terms) / len(neighbor_terms) if neighbor_terms else 0.0
            neighbor_penalty = w_neighbor * neighbor_mean
            throughput_bonus = (
                throughput_weight * (float(arrived_this_step) / max(1.0, float(len(self.tls_ids))))
                if use_throughput_bonus and arrived_this_step > 0
                else 0.0
            )

            if reward_variant == "queue_wait":
                vehicle_component = queue_level + wait_level + neighbor_penalty - throughput_bonus
                reward = -(vehicle_component + pedestrian_penalty)
            elif reward_variant == "pressure":
                vehicle_component = pressure_abs_norm
                reward = -vehicle_component - pedestrian_penalty + throughput_bonus
            elif reward_variant == "pressure_wait_time_loss":
                positive_component = (
                    w_pressure_improvement * pressure_improvement
                    + w_queue_improvement * queue_improvement
                    + w_wait_improvement * wait_improvement
                    + throughput_bonus
                )
                level_penalty = (
                    w_queue_level * queue_level
                    + w_wait_level * wait_level
                    + w_time_loss * time_loss_level
                    + neighbor_penalty
                )
                vehicle_component = level_penalty - positive_component
                reward = positive_component - level_penalty - pedestrian_penalty
            else:
                raise ValueError(f"Unsupported REWARD_VARIANT: {reward_variant}")

            stuck_phase_penalty = 0.0
            switch_penalty = 0.0
            if (
                bool(getattr(self.obs_cfg, "reward_stuck_phase_penalty_enabled", False))
                and float(local.get("time_since_switch", 0.0))
                >= float(getattr(self.obs_cfg, "reward_stuck_phase_after_seconds", 60))
                and (float(local.get("queue", 0.0)) > 0.0 or float(local.get("waiting_time", 0.0)) > 0.0)
            ):
                stuck_phase_penalty = float(getattr(self.obs_cfg, "reward_stuck_phase_penalty", 0.0))
                reward -= stuck_phase_penalty
            if (
                bool(getattr(self.obs_cfg, "reward_switch_penalty_enabled", True))
                and tls_id in self.last_switch_actions_this_step
            ):
                switch_penalty = float(getattr(self.obs_cfg, "reward_switch_penalty", 0.0))
                reward -= switch_penalty
            rewards[tls_id] = reward
            self.prev_waiting_sum_by_tls[tls_id] = wait_sum
            self.prev_queue_by_tls[tls_id] = float(local.get("queue", 0.0))
            self.prev_waiting_avg_by_tls[tls_id] = float(local.get("waiting_time", 0.0))
            self.prev_pressure_abs_by_tls[tls_id] = pressure_abs
            per_tls_breakdown[tls_id] = {
                "reward_variant": reward_variant,
                "queue_penalty": queue_level,
                "wait_penalty": wait_level,
                "vehicle_queue_penalty": queue_level,
                "vehicle_wait_penalty": wait_level,
                "neighbor_penalty": neighbor_penalty,
                "delta_wait_component": delta_wait / max(1.0, lane_count) / wait_norm,
                "pressure_abs_norm": pressure_abs_norm,
                "pressure_improvement": pressure_improvement,
                "queue_improvement": queue_improvement,
                "wait_improvement": wait_improvement,
                "time_loss_component": time_loss_level,
                "throughput_bonus": throughput_bonus,
                "vehicle_reward_component": vehicle_component,
                "pedestrian_penalty": pedestrian_penalty,
                "stuck_phase_penalty": stuck_phase_penalty,
                "switch_penalty": switch_penalty,
                "total_reward": reward,
            }
        self.last_reward_breakdown = self._aggregate_reward_breakdown(per_tls_breakdown)
        return rewards

    def _compute_pedestrian_reward_penalty(self, pedestrian_metrics: dict) -> float:
        if not bool(getattr(self.obs_cfg, "reward_use_pedestrians", False)):
            return 0.0
        if not bool(getattr(self.obs_cfg, "pedestrian_reward_enabled", True)):
            return 0.0
        if not bool(pedestrian_metrics.get("pedestrian_waiting_time_available", True)):
            return 0.0

        norm = max(1e-6, float(getattr(self.obs_cfg, "pedestrian_reward_normalization", 30.0)))
        wait_weight = float(
            getattr(
                self.obs_cfg,
                "w_pedestrian_wait",
                getattr(self.obs_cfg, "reward_pedestrian_wait_weight", 0.10),
            )
        )
        running_weight = float(getattr(self.obs_cfg, "reward_pedestrian_running_weight", 0.02))
        blocked_weight = float(
            getattr(
                self.obs_cfg,
                "w_pedestrian_queue",
                getattr(self.obs_cfg, "reward_pedestrian_blocked_weight", 0.05),
            )
        )

        avg_wait = _safe_float(pedestrian_metrics.get("pedestrian_avg_waiting_time"), 0.0)
        running = _safe_float(pedestrian_metrics.get("pedestrian_running"), 0.0)
        waiting_count = _safe_float(pedestrian_metrics.get("pedestrian_waiting_count"), 0.0)

        penalty = (
            wait_weight * (avg_wait / norm)
            + running_weight * (running / norm)
            + blocked_weight * (waiting_count / norm)
        )
        if not np.isfinite(penalty):
            return 0.0
        max_share = float(getattr(self.obs_cfg, "pedestrian_priority_max_share", 0.20))
        return max(0.0, min(float(penalty), max(0.0, max_share)))

    def _aggregate_reward_breakdown(self, per_tls: Dict[str, dict]) -> dict:
        if not per_tls:
            return {
                "queue_penalty": 0.0,
                "wait_penalty": 0.0,
                "vehicle_queue_penalty": 0.0,
                "vehicle_wait_penalty": 0.0,
                "neighbor_penalty": 0.0,
                "delta_wait_component": 0.0,
                "pressure_abs_norm": 0.0,
                "pressure_improvement": 0.0,
                "queue_improvement": 0.0,
                "wait_improvement": 0.0,
                "time_loss_component": 0.0,
                "throughput_bonus": 0.0,
                "pedestrian_penalty": 0.0,
                "switch_penalty": 0.0,
                "stuck_phase_penalty": 0.0,
                "total_reward": 0.0,
                "avg_vehicle_reward_component": 0.0,
                "avg_pedestrian_reward_component": 0.0,
                "pedestrian_reward_share": 0.0,
                "vehicle_component": 0.0,
                "pedestrian_wait_component": 0.0,
                "pedestrian_share": 0.0,
                "per_tls": {},
            }

        def mean_key(key: str) -> float:
            return float(np.mean([float(item.get(key, 0.0)) for item in per_tls.values()]))

        vehicle_component = mean_key("vehicle_reward_component")
        pedestrian_component = mean_key("pedestrian_penalty")
        denom = max(abs(vehicle_component) + abs(pedestrian_component), 1.0)
        pedestrian_share = abs(pedestrian_component) / denom if denom > 1e-12 else 0.0
        warning = ""
        max_share = float(getattr(self.obs_cfg, "pedestrian_priority_max_share", 0.20))
        if pedestrian_share > max_share:
            warning = "WARNING: pedestrian reward component is too large; vehicle priority may be lost."
            if not self._pedestrian_reward_warning_printed:
                print(warning)
                self._pedestrian_reward_warning_printed = True
        return {
            "queue_penalty": mean_key("queue_penalty"),
            "wait_penalty": mean_key("wait_penalty"),
            "vehicle_queue_penalty": mean_key("vehicle_queue_penalty"),
            "vehicle_wait_penalty": mean_key("vehicle_wait_penalty"),
            "neighbor_penalty": mean_key("neighbor_penalty"),
            "delta_wait_component": mean_key("delta_wait_component"),
            "pressure_abs_norm": mean_key("pressure_abs_norm"),
            "pressure_improvement": mean_key("pressure_improvement"),
            "queue_improvement": mean_key("queue_improvement"),
            "wait_improvement": mean_key("wait_improvement"),
            "time_loss_component": mean_key("time_loss_component"),
            "throughput_bonus": mean_key("throughput_bonus"),
            "pedestrian_penalty": pedestrian_component,
            "stuck_phase_penalty": mean_key("stuck_phase_penalty"),
            "switch_penalty": mean_key("switch_penalty"),
            "total_reward": mean_key("total_reward"),
            "avg_vehicle_reward_component": vehicle_component,
            "avg_pedestrian_reward_component": pedestrian_component,
            "pedestrian_reward_share": float(pedestrian_share),
            "vehicle_component": vehicle_component,
            "pedestrian_wait_component": pedestrian_component,
            "pedestrian_share": float(pedestrian_share),
            "warning": warning,
            "reward_variant": str(getattr(self.obs_cfg, "reward_variant", params.REWARD_VARIANT)),
            "note": "No queue/wait observed in short smoke run." if abs(vehicle_component) < 1e-12 else "",
            "per_tls": per_tls,
        }

    def _build_observations(self, stats: Dict[str, dict]) -> Dict[str, np.ndarray]:
        observations = {}
        for tls_id, local in stats.items():
            aggs = aggregate_neighbors(tls_id, stats, self.neighbors)
            phase_onehot = encode_phase_onehot(
                int(local.get("current_phase_index", 0)),
                int(local.get("num_phases", 1)),
                self.max_phases_global,
            )
            observations[tls_id] = build_observation(
                tls_id=tls_id,
                local_stats=local,
                neighbor_aggs=aggs,
                phase_onehot=phase_onehot,
                time_since_switch=float(local.get("time_since_switch", 0.0)),
                obs_cfg=self.obs_cfg,
            )
        self._record_observation_stats(observations)
        return observations

    def _record_observation_stats(self, observations: Dict[str, np.ndarray]) -> None:
        if not observations:
            return
        values = np.stack([np.asarray(obs, dtype=np.float64) for obs in observations.values()])
        nan_count = int(np.isnan(values).sum())
        inf_count = int(np.isinf(values).sum())
        if nan_count or inf_count:
            raise RuntimeError(
                f"Observation contains NaN/Inf values: nan_count={nan_count}, inf_count={inf_count}"
            )
        if self._obs_stats is None:
            dim = int(values.shape[1])
            self._obs_stats = {
                "obs_dim": dim,
                "count": 0,
                "sum": np.zeros(dim, dtype=np.float64),
                "sumsq": np.zeros(dim, dtype=np.float64),
                "min": np.full(dim, np.inf, dtype=np.float64),
                "max": np.full(dim, -np.inf, dtype=np.float64),
                "nan_count": 0,
                "inf_count": 0,
            }
        stats = self._obs_stats
        stats["count"] += int(values.shape[0])
        stats["sum"] += values.sum(axis=0)
        stats["sumsq"] += np.square(values).sum(axis=0)
        stats["min"] = np.minimum(stats["min"], values.min(axis=0))
        stats["max"] = np.maximum(stats["max"], values.max(axis=0))

    def _save_observation_stats(self) -> None:
        stats = self._obs_stats
        if not stats or self.obs_cfg is None:
            return
        try:
            logs_dir = Path(getattr(self.obs_cfg, "logs_dir"))
        except Exception:
            return
        count = max(1, int(stats["count"]))
        mean = stats["sum"] / count
        variance = np.maximum((stats["sumsq"] / count) - np.square(mean), 0.0)
        std = np.sqrt(variance)
        zero_variance = [idx for idx, value in enumerate(std.tolist()) if abs(float(value)) <= 1e-12]
        payload = {
            "obs_dim": int(stats["obs_dim"]),
            "count": int(stats["count"]),
            "min": [float(x) for x in stats["min"].tolist()],
            "max": [float(x) for x in stats["max"].tolist()],
            "mean": [float(x) for x in mean.tolist()],
            "std": [float(x) for x in std.tolist()],
            "nan_count": int(stats["nan_count"]),
            "inf_count": int(stats["inf_count"]),
            "zero_variance_features": zero_variance,
        }
        try:
            logs_dir.mkdir(parents=True, exist_ok=True)
            (logs_dir / "observation_stats.json").write_text(
                json.dumps(payload, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
        except Exception:
            pass
